(() => {
  'use strict';

  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const canvas = $('#plan');
  const ctx = canvas.getContext('2d');
  const wrap = $('#canvas-wrap');
  const STORAGE_KEY = 'aiad-lab-layout-v2';
  const LEGACY_STORAGE_KEY = 'aiad-lab-layout-v1';
  const palette = { wall:'#465167', glass:'#42b8d8', blue:'#3276e8', red:'#db4b52', green:'#2e9d74', ink:'#182238', muted:'#738097' };

  const targetCounts = {gradDesk:6,gradChair:6,underDesk:4,underChair:4,profLarge:1,profSmall:2,monitor:1,meetingTable:1,sofa:1,fridge:1};
  const initial = () => ({
    version:'2.0.0', projectName:'가변형 회의 공간형', unit:'cm', gridSize:50,
    orientation:{rotationDegrees:-90,label:'왼쪽으로 90도 회전'},
    roomBoundary:{type:'polygon',closed:true,vertices:[
      {id:'v1',x:0,y:920},{id:'v2',x:0,y:0},{id:'v3',x:180,y:0},
      {id:'v4',x:180,y:100},{id:'v5',x:310,y:100},{id:'v6',x:310,y:20},
      {id:'v7',x:920,y:20},{id:'v8',x:920,y:920},{id:'v9',x:300,y:920},
      {id:'v10',x:300,y:690},{id:'v11',x:130,y:690},{id:'v12',x:130,y:920}
    ]},
    spaces:[
      {id:'space-grad',name:'대학원생실',type:'graduate',bounds:{x:0,y:0,w:520,h:920}},
      {id:'space-under',name:'학부생실 및 회의 공간',type:'undergrad',bounds:{x:520,y:20,w:400,h:900}},
      {id:'space-common',name:'복도 또는 공용 공간',type:'common',bounds:{x:300,y:690,w:220,h:230}}
    ],
    walls:[],glassWalls:[{id:'glass-1',type:'glass-wall',name:'중앙 유리 파티션',start:{x:520,y:920},end:{x:520,y:20},thickness:10,locked:false,opacity:.72}],
    doors:[{id:'door-1',type:'door',name:'주 출입문',x:330,y:920,width:90,rotation:0,openingDirection:'inward-up-left',openingAngle:90,locked:false}],
    windows:[],structures:[], furniture:[], targetCounts:{...targetCounts}, layouts:{},initialized:false,
    settings:{snap:true,objectSnap:true,zoom:1,showGrid:true,showDimensions:true,wallThickness:12,minAisleWidth:80}, createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()
  });
  let state = load() || initial();
  let view = {zoom:1, panX:0, panY:0};
  let tool = 'select', selected = null, dragging = null, hovered = null, measurePoints = [], spaceDown = false;
  let history = [], future = [], saveTimer, toastTimer, renderWarnings=[];

  const furnitureTypes = {
    gradDesk:{name:'대학원생용 책상',w:140,h:70,color:'#79a8d8',seats:0,space:'graduate'},gradChair:{name:'대학원생용 의자',w:60,h:60,color:'#69b394',seats:1,space:'graduate'},
    underDesk:{name:'학부생용 책상',w:120,h:60,color:'#9988d0',seats:0,space:'undergrad'},underChair:{name:'학부생용 의자',w:60,h:60,color:'#83bda4',seats:1,space:'undergrad'},
    profLarge:{name:'교수님용 큰 책상',w:180,h:80,color:'#b47d58',seats:1,space:'common'},profSmall:{name:'교수님용 작은 책상',w:120,h:60,color:'#bd916e',seats:1,space:'graduate'},
    monitor:{name:'대형 모니터',w:160,h:20,color:'#459bb5',seats:0,space:'undergrad'},meetingTable:{name:'회의용 테이블',w:180,h:90,color:'#d99a55',seats:0,space:'undergrad'},meetingChair:{name:'회의용 의자',w:60,h:60,color:'#d9b16f',seats:1,space:'undergrad'},
    sofa:{name:'소파',w:180,h:80,color:'#c7839f',seats:3,space:'undergrad'},fridge:{name:'냉장고',w:80,h:80,color:'#83a9bc',seats:0,space:'undergrad'},
    cabinet:{name:'캐비닛',w:90,h:45,color:'#8793a7',seats:0,space:'common'},shelf:{name:'책장',w:120,h:40,color:'#b98c68',seats:0,space:'common'},printer:{name:'프린터',w:60,h:60,color:'#9d826c',seats:0,space:'common'},whiteboard:{name:'이동식 화이트보드',w:140,h:20,color:'#7596a7',seats:0,space:'common'}
  };

  function uid(prefix){ return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`; }
  function clone(v){ return JSON.parse(JSON.stringify(v)); }
  function snapshot(){ history.push(clone(state)); if(history.length>50) history.shift(); future=[]; }
  function commit(message){ state.updatedAt=new Date().toISOString(); clearTimeout(saveTimer); $('#autosave').textContent='저장 중…'; saveTimer=setTimeout(()=>{ try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#autosave').textContent='모든 변경사항 저장됨';}catch(e){showToast('자동 저장 공간이 부족합니다.');} },500); updateAnalysis(); updateProperties(); render(); if(message) showToast(message); }
  function load(){
    try{
      const raw=localStorage.getItem(STORAGE_KEY);if(raw)return normalizeV2(JSON.parse(raw));
      const legacy=localStorage.getItem(LEGACY_STORAGE_KEY);if(!legacy)return null;
      const old=JSON.parse(legacy);localStorage.setItem(`${LEGACY_STORAGE_KEY}-backup-${Date.now()}`,legacy);
      return migrateLegacy(old,confirm('기존 세로형 자동 저장 데이터를 발견했습니다. 왼쪽으로 90도 회전하여 새 형식으로 가져올까요?'));
    }catch(e){return null;}
  }
  function normalizeV2(data){
    const base=initial();data.version='2.0.0';data.orientation=data.orientation||base.orientation;data.spaces=data.spaces||base.spaces;data.glassWalls=data.glassWalls||(data.glassWall?[data.glassWall]:base.glassWalls);delete data.glassWall;data.walls=data.walls||[];data.windows=data.windows||[];data.doors=data.doors||base.doors;data.structures=data.structures||[];data.furniture=data.furniture||[];data.targetCounts={...targetCounts,...data.targetCounts};data.layouts=data.layouts||{};data.settings={...base.settings,...data.settings};data.initialized=true;return data;
  }
  function migrateLegacy(old,rotate=true){
    const data=clone(old);if(rotate)rotateData(data,-90,false);data.version='2.0.0';data.orientation={rotationDegrees:rotate?-90:0,label:rotate?'왼쪽으로 90도 회전':'기존 방향'};data.glassWalls=data.glassWalls||(data.glassWall?[data.glassWall]:[]);delete data.glassWall;
    const typeMap={desk:'underDesk',desk2:'gradDesk',chair:'underChair',table:'meetingTable'};(data.furniture||[]).forEach(o=>{o.type=typeMap[o.type]||o.type;o.space=o.space||'undergrad';});return normalizeV2(data);
  }
  function rotatePoint(p,degrees){const rad=degrees*Math.PI/180,c=Math.cos(rad),s=Math.sin(rad);return{x:p.x*c-p.y*s,y:p.x*s+p.y*c};}
  function rotateData(data,degrees,normalize=true){
    const refs=[];(data.roomBoundary?.vertices||[]).forEach(p=>refs.push(p));(data.glassWalls||(data.glassWall?[data.glassWall]:[])).forEach(g=>{refs.push(g.start,g.end)});(data.doors||[]).forEach(ref=>refs.push(ref));(data.windows||[]).forEach(ref=>refs.push(ref));(data.structures||[]).forEach(ref=>refs.push(ref));(data.furniture||[]).forEach(ref=>refs.push(ref));
    const rotated=refs.map(p=>rotatePoint(p,degrees)),minX=normalize?Math.min(...rotated.map(p=>p.x)):0,minY=normalize?Math.min(...rotated.map(p=>p.y)):0;refs.forEach((p,i)=>{p.x=Math.round(rotated[i].x-minX);p.y=Math.round(rotated[i].y-minY);if(p.rotation!=null)p.rotation=(p.rotation+degrees+360)%360;});
    (data.spaces||[]).forEach(s=>{const corners=[{x:s.bounds.x,y:s.bounds.y},{x:s.bounds.x+s.bounds.w,y:s.bounds.y+s.bounds.h}].map(p=>rotatePoint(p,degrees));s.bounds={x:Math.min(...corners.map(p=>p.x))-minX,y:Math.min(...corners.map(p=>p.y))-minY,w:Math.abs(corners[1].x-corners[0].x),h:Math.abs(corners[1].y-corners[0].y)};});
  }
  function undo(){ if(!history.length)return showToast('되돌릴 작업이 없습니다.');future.push(clone(state));state=history.pop();selected=null;commit(); }
  function redo(){ if(!future.length)return showToast('다시 실행할 작업이 없습니다.');history.push(clone(state));state=future.pop();selected=null;commit(); }
  function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800);}
  function snap(v){return state.settings.snap?Math.round(v/state.gridSize)*state.gridSize:v;}
  function worldToScreen(p){return{x:p.x*view.zoom+view.panX,y:p.y*view.zoom+view.panY};}
  function screenToWorld(p){return{x:(p.x-view.panX)/view.zoom,y:(p.y-view.panY)/view.zoom};}
  function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}

  function resize(){const r=wrap.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);render();}
  function fitView(){const r=wrap.getBoundingClientRect(),vs=state.roomBoundary.vertices;const minX=Math.min(...vs.map(v=>v.x)),maxX=Math.max(...vs.map(v=>v.x)),minY=Math.min(...vs.map(v=>v.y)),maxY=Math.max(...vs.map(v=>v.y));view.zoom=Math.min((r.width-150)/(maxX-minX),(r.height-100)/(maxY-minY));view.zoom=Math.max(.25,Math.min(2,view.zoom));view.panX=(r.width-(maxX-minX)*view.zoom)/2-minX*view.zoom;view.panY=(r.height-(maxY-minY)*view.zoom)/2-minY*view.zoom;updateZoom();render();}
  function updateZoom(){$('#zoom-label').textContent=`${Math.round(view.zoom*100)}%`;$('#scale-label').textContent=`1:${Math.max(10,Math.round(50/view.zoom/10)*10)}`;}
  function setZoom(z,center){const old=view.zoom;z=Math.max(.25,Math.min(4,z));center=center||{x:wrap.clientWidth/2,y:wrap.clientHeight/2};const wx=(center.x-view.panX)/old,wy=(center.y-view.panY)/old;view.zoom=z;view.panX=center.x-wx*z;view.panY=center.y-wy*z;updateZoom();render();}

  function render(){
    const w=wrap.clientWidth,h=wrap.clientHeight;renderWarnings=getWarnings();ctx.clearRect(0,0,w,h);drawGrid(w,h);
    ctx.save();ctx.translate(view.panX,view.panY);ctx.scale(view.zoom,view.zoom);
    drawRoom();drawSpaces();state.glassWalls.forEach(drawGlass);state.structures.forEach(drawStructure);state.doors.forEach(drawDoor);state.furniture.forEach(drawFurniture);drawMeasurements();ctx.restore();
  }
  function drawGrid(w,h){if(!state.settings.showGrid)return;const step=Math.max(12,state.gridSize*view.zoom);ctx.save();ctx.strokeStyle='#d7dde6';ctx.lineWidth=1;ctx.globalAlpha=.65;const ox=((view.panX%step)+step)%step,oy=((view.panY%step)+step)%step;ctx.beginPath();for(let x=ox;x<w;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let y=oy;y<h;y+=step){ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();ctx.restore();}
  function pathRoom(){const vs=state.roomBoundary.vertices;ctx.beginPath();vs.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.closePath();}
  function drawRoom(){const invalid=selfIntersects(state.roomBoundary.vertices);pathRoom();ctx.fillStyle=invalid?'rgba(219,75,82,.06)':'rgba(255,255,255,.82)';ctx.fill();ctx.strokeStyle=invalid?palette.red:palette.wall;ctx.lineWidth=8/view.zoom;ctx.lineJoin='round';ctx.stroke();
    if(tool==='vertices'){state.roomBoundary.vertices.forEach((v,i)=>{ctx.beginPath();ctx.arc(v.x,v.y,7/view.zoom,0,Math.PI*2);ctx.fillStyle=selected?.kind==='vertex'&&selected.index===i?'#3276e8':'#fff';ctx.fill();ctx.strokeStyle='#3276e8';ctx.lineWidth=2/view.zoom;ctx.stroke();});}
    if(tool==='walls'||selected?.kind==='wall'){const vs=state.roomBoundary.vertices;vs.forEach((v,i)=>{const n=vs[(i+1)%vs.length],active=selected?.kind==='wall'&&selected.index===i;ctx.beginPath();ctx.moveTo(v.x,v.y);ctx.lineTo(n.x,n.y);ctx.strokeStyle=active?palette.blue:'rgba(50,118,232,.45)';ctx.lineWidth=(active?7:3)/view.zoom;ctx.stroke();if(state.settings.showDimensions){const m={x:(v.x+n.x)/2,y:(v.y+n.y)/2};ctx.fillStyle=palette.ink;ctx.font=`${10/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillText(`${Math.round(distance(v,n))} cm`,m.x,m.y-9/view.zoom);}});}
    if(invalid){const p=state.roomBoundary.vertices[0];ctx.fillStyle=palette.red;ctx.font=`${12/view.zoom}px sans-serif`;ctx.fillText('외곽선이 교차합니다',p.x,p.y-18/view.zoom);}
  }
  function drawSpaces(){ctx.save();pathRoom();ctx.clip();state.spaces.forEach(s=>{const b=s.bounds,active=selected?.kind==='space'&&selected.id===s.id;ctx.fillStyle=s.type==='graduate'?'rgba(50,118,232,.045)':s.type==='undergrad'?'rgba(129,93,205,.04)':'rgba(243,169,59,.055)';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.fillStyle=active?palette.blue:palette.muted;ctx.font=`${active?13:11}px sans-serif`;ctx.textAlign='center';ctx.fillText(s.name,b.x+b.w/2,b.y+42/view.zoom);});ctx.restore();}
  function drawGlass(g){ctx.save();ctx.globalAlpha=g.opacity??.72;ctx.strokeStyle='rgba(76,201,232,.28)';ctx.lineWidth=Math.max(g.thickness,16/view.zoom);ctx.beginPath();ctx.moveTo(g.start.x,g.start.y);ctx.lineTo(g.end.x,g.end.y);ctx.stroke();ctx.strokeStyle=palette.glass;ctx.lineWidth=3/view.zoom;ctx.setLineDash([12/view.zoom,7/view.zoom]);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.save();ctx.translate((g.start.x+g.end.x)/2,(g.start.y+g.end.y)/2);ctx.fillStyle=palette.muted;ctx.font=`${11/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillText('유리 파티션',0,-10/view.zoom);ctx.restore();if(selected?.kind==='glass'&&selected.id===g.id){[g.start,g.end].forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,7/view.zoom,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=palette.blue;ctx.lineWidth=2/view.zoom;ctx.stroke();});}ctx.restore();}
  function drawDoor(d){ctx.save();const warning=renderWarnings.some(w=>w.ids.includes(d.id)),down=(d.openingDirection||'').includes('down'),right=(d.openingDirection||'').includes('right'),sign=down?1:-1,hinge=right?d.width:0;ctx.translate(d.x,d.y);ctx.rotate((d.rotation||0)*Math.PI/180);ctx.strokeStyle=warning?palette.red:palette.green;ctx.lineWidth=3/view.zoom;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(d.width,0);ctx.stroke();ctx.beginPath();ctx.arc(hinge,0,d.width,right?Math.PI:sign*Math.PI/2,right?Math.PI+sign*Math.PI/2:0,sign<0);ctx.strokeStyle=warning?palette.red:'rgba(46,157,116,.65)';ctx.lineWidth=2/view.zoom;ctx.stroke();ctx.beginPath();ctx.moveTo(hinge,0);ctx.lineTo(hinge,sign*d.width);ctx.stroke();if(selected?.kind==='door'&&selected.id===d.id){ctx.beginPath();ctx.arc(hinge,0,7/view.zoom,0,Math.PI*2);ctx.fillStyle=palette.blue;ctx.fill();}ctx.restore();}
  function drawStructure(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.fillStyle=o.type==='column'?'#526077':'#cad3de';ctx.fillRect(-o.w/2,-o.h/2,o.w,o.h);ctx.strokeStyle=selected?.id===o.id?palette.blue:'#7d8999';ctx.lineWidth=(selected?.id===o.id?3:1)/view.zoom;ctx.strokeRect(-o.w/2,-o.h/2,o.w,o.h);ctx.fillStyle=o.type==='column'?'#fff':palette.ink;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${11/view.zoom}px sans-serif`;ctx.fillText(o.type==='column'?'기둥':'AC',0,0);ctx.restore();}
  function drawFurniture(o){const warning=renderWarnings.some(w=>w.ids.includes(o.id)),isSelected=selected?.id===o.id||(selected?.kind==='multi'&&selected.ids.includes(o.id)),angle=(o.rotation||0)*Math.PI/180;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(angle);ctx.fillStyle=o.color;ctx.globalAlpha=o.opacity??.88;roundRect(ctx,-o.w/2,-o.h/2,o.w,o.h,Math.min(8,o.h/4));ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=warning?palette.red:isSelected?palette.blue:'rgba(33,48,73,.42)';ctx.lineWidth=(warning||isSelected?3:1.5)/view.zoom;ctx.stroke();if(isSelected&&selected.kind!=='multi'){ctx.beginPath();ctx.arc(0,-o.h/2-18/view.zoom,6/view.zoom,0,Math.PI*2);ctx.fillStyle=palette.blue;ctx.fill();ctx.beginPath();ctx.moveTo(0,-o.h/2);ctx.lineTo(0,-o.h/2-12/view.zoom);ctx.strokeStyle=palette.blue;ctx.lineWidth=2/view.zoom;ctx.stroke();}ctx.rotate(-angle);ctx.fillStyle='#24344f';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.max(10,12/view.zoom)}px sans-serif`;ctx.fillText(o.name,0,0);if(o.locked){ctx.fillStyle=palette.ink;ctx.font=`${12/view.zoom}px sans-serif`;ctx.fillText('🔒',Math.min(o.w,o.h)/2-10/view.zoom,-Math.min(o.w,o.h)/2+10/view.zoom);}ctx.restore();}
  function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect?c.roundRect(x,y,w,h,r):(c.rect(x,y,w,h));}
  function drawMeasurements(){if(!measurePoints.length)return;ctx.save();ctx.strokeStyle=palette.blue;ctx.fillStyle=palette.blue;ctx.lineWidth=2/view.zoom;ctx.setLineDash([7/view.zoom,5/view.zoom]);ctx.beginPath();ctx.moveTo(measurePoints[0].x,measurePoints[0].y);if(measurePoints[1])ctx.lineTo(measurePoints[1].x,measurePoints[1].y);ctx.stroke();measurePoints.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,5/view.zoom,0,Math.PI*2);ctx.fill();});if(measurePoints[1]){const d=distance(measurePoints[0],measurePoints[1]),m={x:(measurePoints[0].x+measurePoints[1].x)/2,y:(measurePoints[0].y+measurePoints[1].y)/2};ctx.setLineDash([]);ctx.font=`${12/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillStyle=palette.ink;ctx.fillText(`${Math.round(d)} cm · ${(d/100).toFixed(2)} m`,m.x,m.y-10/view.zoom);}ctx.restore();}

  function findAt(p){
    for(let i=state.furniture.length-1;i>=0;i--){const o=state.furniture[i];if(inRotatedRect(p,o))return{kind:'furniture',id:o.id};}
    for(let i=state.structures.length-1;i>=0;i--){const o=state.structures[i];if(inRotatedRect(p,o))return{kind:'structure',id:o.id};}
    for(let i=state.doors.length-1;i>=0;i--){const d=state.doors[i];if(distance(p,d)<Math.max(18,d.width/3))return{kind:'door',id:d.id};}
    if(tool==='vertices'){const i=state.roomBoundary.vertices.findIndex(v=>distance(p,v)<12/view.zoom);if(i>=0)return{kind:'vertex',index:i,id:state.roomBoundary.vertices[i].id};}
    if(tool==='walls'){const vs=state.roomBoundary.vertices;let best={index:-1,d:Infinity};vs.forEach((v,i)=>{const d=pointSegmentDistance(p,v,vs[(i+1)%vs.length]);if(d<best.d)best={index:i,d};});if(best.d<15/view.zoom)return{kind:'wall',index:best.index,id:`wall-${best.index}`};}
    for(const g of state.glassWalls){if(distance(p,g.start)<12/view.zoom)return{kind:'glass',id:g.id,endpoint:'start'};if(distance(p,g.end)<12/view.zoom)return{kind:'glass',id:g.id,endpoint:'end'};if(pointSegmentDistance(p,g.start,g.end)<12/view.zoom)return{kind:'glass',id:g.id};}
    for(const s of state.spaces){const b=s.bounds;if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h&&pointInPolygon(p,state.roomBoundary.vertices))return{kind:'space',id:s.id};}
    return null;
  }
  function getObject(sel=selected){if(!sel)return null;if(sel.kind==='furniture')return state.furniture.find(x=>x.id===sel.id);if(sel.kind==='structure')return state.structures.find(x=>x.id===sel.id);if(sel.kind==='door')return state.doors.find(x=>x.id===sel.id);if(sel.kind==='space')return state.spaces.find(x=>x.id===sel.id);if(sel.kind==='glass')return state.glassWalls.find(x=>x.id===sel.id);if(sel.kind==='vertex')return state.roomBoundary.vertices[sel.index];if(sel.kind==='wall'){const a=state.roomBoundary.vertices[sel.index],b=state.roomBoundary.vertices[(sel.index+1)%state.roomBoundary.vertices.length];return{type:'wall',name:`벽 ${sel.index+1}`,start:a,end:b,thickness:state.settings.wallThickness};}return null;}
  function inRotatedRect(p,o){const a=-(o.rotation||0)*Math.PI/180,dx=p.x-o.x,dy=p.y-o.y,x=dx*Math.cos(a)-dy*Math.sin(a),y=dx*Math.sin(a)+dy*Math.cos(a);return Math.abs(x)<=o.w/2&&Math.abs(y)<=o.h/2;}
  function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
  function pointSegmentDistance(p,a,b){const l2=(b.x-a.x)**2+(b.y-a.y)**2;if(!l2)return distance(p,a);let t=((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/l2;t=Math.max(0,Math.min(1,t));return distance(p,{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y)});}

  canvas.addEventListener('pointerdown',e=>{
    canvas.setPointerCapture(e.pointerId);const sp=pointer(e),p=screenToWorld(sp);if(tool==='pan'||spaceDown||e.button===1){dragging={type:'pan',start:sp,panX:view.panX,panY:view.panY};return;}
    if(tool==='measure'){if(measurePoints.length===2)measurePoints=[];measurePoints.push({x:snap(p.x),y:snap(p.y)});render();return;}
    const hit=findAt(p);selected=hit;updateProperties();if(hit&&hit.kind!=='space'){const o=getObject(hit);if(o?.locked)return render();snapshot();if(hit.kind==='vertex')dragging={type:'vertex',start:p,orig:{x:o.x,y:o.y}};else if(hit.kind==='wall')dragging={type:'wall',start:p,origStart:clone(o.start),origEnd:clone(o.end)};else if(hit.kind==='glass')dragging={type:hit.endpoint?'glass-end':'glass',endpoint:hit.endpoint,start:p,origStart:clone(o.start),origEnd:clone(o.end)};else dragging={type:'object',start:p,orig:{x:o.x,y:o.y}};}render();
  });
  function objectSnapPosition(o,x,y){if(!state.settings.objectSnap||selected?.kind!=='furniture')return{x,y};for(const peer of state.furniture){if(peer.id===o.id)continue;if(Math.abs(peer.x-x)<=10)x=peer.x;if(Math.abs(peer.y-y)<=10)y=peer.y;}return{x,y};}
  canvas.addEventListener('pointermove',e=>{if(!dragging)return;const sp=pointer(e);if(dragging.type==='pan'){view.panX=dragging.panX+sp.x-dragging.start.x;view.panY=dragging.panY+sp.y-dragging.start.y;render();return;}const p=screenToWorld(sp),dx=p.x-dragging.start.x,dy=p.y-dragging.start.y,o=getObject();if(!o)return;if(dragging.type==='vertex'){let nx=dragging.orig.x+dx,ny=dragging.orig.y+dy;if(e.shiftKey){Math.abs(dx)>Math.abs(dy)?ny=dragging.orig.y:nx=dragging.orig.x;}o.x=e.ctrlKey||e.metaKey?nx:snap(nx);o.y=e.ctrlKey||e.metaKey?ny:snap(ny);}else if(dragging.type==='wall'||dragging.type==='glass'){o.start.x=snap(dragging.origStart.x+dx);o.start.y=snap(dragging.origStart.y+dy);o.end.x=snap(dragging.origEnd.x+dx);o.end.y=snap(dragging.origEnd.y+dy);}else if(dragging.type==='glass-end'){const target=dragging.endpoint==='start'?o.start:o.end;target.x=snap(p.x);target.y=snap(p.y);}else{const pos=objectSnapPosition(o,snap(dragging.orig.x+dx),snap(dragging.orig.y+dy));o.x=pos.x;o.y=pos.y;}updateProperties();updateAnalysis();render();});
  canvas.addEventListener('pointerup',()=>{if(dragging&&dragging.type!=='pan')commit();dragging=null;});
  canvas.addEventListener('dblclick',e=>{if(tool!=='vertices')return;const p=screenToWorld(pointer(e)),vs=state.roomBoundary.vertices;let best={i:-1,d:Infinity};for(let i=0;i<vs.length;i++){const d=pointSegmentDistance(p,vs[i],vs[(i+1)%vs.length]);if(d<best.d)best={i,d};}if(best.d<18/view.zoom){snapshot();vs.splice(best.i+1,0,{id:uid('v'),x:snap(p.x),y:snap(p.y)});selected={kind:'vertex',index:best.i+1};commit('새 꼭짓점을 추가했습니다.');}});
  canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(view.zoom*(e.deltaY>0?.9:1.1),pointer(e));},{passive:false});

  function setTool(next){tool=next;measurePoints=[];$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#mode-label').textContent={select:'가구 배치 · 객체 선택',vertices:'도면 편집 · 꼭짓점',walls:'도면 편집 · 벽선',measure:'거리 측정',pan:'화면 이동'}[tool];canvas.style.cursor=tool==='pan'?'grab':['vertices','walls'].includes(tool)?'crosshair':'default';render();}
  $('#tools').addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool);});
  $('#furniture-list').addEventListener('click',e=>{const b=e.target.closest('[data-furniture]');if(!b)return;addFurniture(b.dataset.furniture);});
  function addFurniture(type){const t=furnitureTypes[type],center=screenToWorld({x:wrap.clientWidth/2,y:wrap.clientHeight/2});snapshot();const count=state.furniture.filter(o=>o.type===type).length+1,o={id:uid(type),type,name:`${t.name} ${count}`,x:snap(center.x),y:snap(center.y),w:t.w,h:t.h,rotation:0,color:t.color,seats:t.seats,space:t.space,opacity:1,locked:false,groupId:null};state.furniture.push(o);selected={kind:'furniture',id:o.id};setTool('select');commit(`${t.name}을(를) 추가했습니다.`);}
  function makeFurniture(type,x,y,rotation=0){const t=furnitureTypes[type],count=(state.furniture||[]).filter(o=>o.type===type).length+1;return{id:uid(type),type,name:`${t.name} ${count}`,x,y,w:t.w,h:t.h,rotation,color:t.color,seats:t.seats,space:t.space,opacity:1,locked:false,groupId:null};}
  function buildLayout(kind){state.furniture=[];const add=(type,x,y,r=0)=>state.furniture.push(makeFurniture(type,x,y,r));
    const gradX=[80,240,400],gradY=kind==='meeting'?[180,390]:[170,370];gradY.forEach(y=>gradX.forEach(x=>{add('gradDesk',x,y);add('gradChair',x,y+70);}));add('profSmall',150,570);add('profSmall',390,570);add('profLarge',400,740);
    const under=kind==='meeting'?[[630,180],[630,350],[840,180],[840,350]]:kind==='flex'?[[630,180],[630,350],[840,180],[840,350]]:[[620,180],[810,180],[620,350],[810,350]];under.forEach(([x,y])=>{add('underDesk',x,y,90);add('underChair',x<700?x+70:x-70,y);});
    add('monitor',900,560,90);const tableRotation=kind==='flex'?90:0;add('meetingTable',720,kind==='study'?570:560,tableRotation);const chairPositions=tableRotation?[[620,500],[620,620],[820,500],[820,620],[720,410],[850,720]]:[[630,470],[720,440],[810,470],[630,650],[720,680],[810,650]];chairPositions.slice(0,kind==='study'?4:6).forEach(([x,y])=>add('meetingChair',x,y));add('sofa',640,720);add('fridge',860,840);state.projectName={study:'학습 중심형',meeting:'회의 중심형',flex:'가변형 회의 공간형'}[kind];state.activeLayout=kind;}
  function applyLayout(kind){snapshot();buildLayout(kind);selected=null;$$('[data-layout]').forEach(b=>b.classList.toggle('active',b.dataset.layout===kind));commit(`${state.projectName} 배치안을 적용했습니다.`);fitView();}
  $('#layout-presets').addEventListener('click',e=>{const b=e.target.closest('[data-layout]');if(b&&confirm(`${b.querySelector('b').textContent} 배치안으로 현재 가구를 교체할까요?`))applyLayout(b.dataset.layout);});
  $('.layout-actions').addEventListener('click',e=>{const b=e.target.closest('[data-layout-action]');if(!b)return;const action=b.dataset.layoutAction;if(action==='save'){const name=prompt('현재 배치안 이름',state.projectName);if(name){state.layouts[name]=clone(state.furniture);state.projectName=name;commit('현재 배치안을 저장했습니다.');}}if(action==='duplicate'){const name=`${state.projectName} 복사본`;state.layouts[name]=clone(state.furniture);state.projectName=name;commit('배치안을 복제했습니다.');}if(action==='compare')showComparison();});
  function layoutStats(kind){const backup=state.furniture,oldName=state.projectName,oldActive=state.activeLayout;buildLayout(kind);const t=targetSummary(),area=polygonArea(state.roomBoundary.vertices)/10000,occ=state.furniture.reduce((s,o)=>s+o.w*o.h,0)/10000,w=getWarnings().length,seats=state.furniture.reduce((s,o)=>s+(o.seats||0),0);state.furniture=backup;state.projectName=oldName;state.activeLayout=oldActive;return{target:t.percent,occupancy:Math.round(occ/area*100),warnings:w,seats};}
  function showComparison(){const kinds=['study','meeting','flex'],names=['학습 중심형','회의 중심형','가변형 회의 공간형'],stats=kinds.map(layoutStats);$('#comparison-table').innerHTML=`<div class="comparison-grid"><b>비교 항목</b>${names.map(n=>`<b>${n}</b>`).join('')}<span>전체 좌석</span>${stats.map(s=>`<span>${s.seats}석</span>`).join('')}<span>목표 충족률</span>${stats.map(s=>`<span class="${s.target===100?'best':''}">${s.target}%</span>`).join('')}<span>가구 점유율</span>${stats.map(s=>`<span>${s.occupancy}%</span>`).join('')}<span>경고 수</span>${stats.map(s=>`<span>${s.warnings}건</span>`).join('')}</div>`;$('#compare-dialog').showModal();}
  $$('.structure-list [data-add]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.add;if(type==='door'){snapshot();const d={id:uid('door'),type:'door',name:'출입문',x:330,y:920,width:90,rotation:0,openingDirection:'inward-up-left',openingAngle:90,locked:false};state.doors.push(d);selected={kind:'door',id:d.id};commit('문을 추가했습니다.');return;}const center=screenToWorld({x:wrap.clientWidth/2,y:wrap.clientHeight/2}),o={id:uid(type),type,name:type==='column'?'기둥':'에어컨',x:snap(center.x),y:snap(center.y),w:type==='column'?50:110,h:type==='column'?50:35,rotation:0,space:'common',color:type==='column'?'#526077':'#cad3de',locked:false};snapshot();state.structures.push(o);selected={kind:'structure',id:o.id};commit(`${o.name}을(를) 추가했습니다.`);}));

  function updateProperties(){
    const o=getObject(),form=$('#property-form'),empty=$('#empty-properties');if(!o){form.hidden=true;empty.hidden=false;$('#selection-badge').textContent='없음';return;}form.hidden=false;empty.hidden=true;
    const linear=['glass','wall'].includes(selected.kind),isSpace=selected.kind==='space';$('#selection-badge').textContent={vertex:'꼭짓점',glass:'유리벽',wall:'일반 벽',door:'문',space:'공간'}[selected.kind]||o.name||o.type;$('#prop-name').value=o.name||o.id;
    $('#prop-x').value=Math.round(linear?o.start.x:isSpace?o.bounds.x:o.x);$('#prop-y').value=Math.round(linear?o.start.y:isSpace?o.bounds.y:o.y);$('#prop-w').value=Math.round(linear?distance(o.start,o.end):selected.kind==='door'?o.width:isSpace?o.bounds.w:o.w||1);$('#prop-h').value=Math.round(linear?o.thickness:selected.kind==='door'?o.openingAngle:isSpace?o.bounds.h:o.h||1);
    $('#prop-rotation').value=o.rotation||0;$('#rotation-value').textContent=`${o.rotation||0}°`;$('#prop-space').value=isSpace?o.type:(o.space||'common');$('#prop-color').value=/^#[0-9a-f]{6}$/i.test(o.color||'')?o.color:'#8793a7';$('#prop-locked').checked=!!o.locked;
    $('#prop-name').disabled=['vertex','wall'].includes(selected.kind);$('#prop-space').disabled=!['furniture','structure','space'].includes(selected.kind);$('#prop-color').disabled=!['furniture','structure'].includes(selected.kind);$('#prop-locked').disabled=['vertex','wall','space'].includes(selected.kind);$('#prop-h').disabled=selected.kind==='vertex';$('#prop-rotation').disabled=['vertex','glass','wall','space'].includes(selected.kind);$('#wall-controls').hidden=!linear;$('#door-direction-field').hidden=selected.kind!=='door';if(selected.kind==='door')$('#prop-door-direction').value=o.openingDirection;
  }
  function setLineLength(o,length,anchor){length=Math.max(1,length);const old=distance(o.start,o.end)||1,ux=(o.end.x-o.start.x)/old,uy=(o.end.y-o.start.y)/old;if(anchor==='end'){o.start.x=o.end.x-ux*length;o.start.y=o.end.y-uy*length;}else if(anchor==='center'){const cx=(o.start.x+o.end.x)/2,cy=(o.start.y+o.end.y)/2;o.start.x=cx-ux*length/2;o.start.y=cy-uy*length/2;o.end.x=cx+ux*length/2;o.end.y=cy+uy*length/2;}else{o.end.x=o.start.x+ux*length;o.end.y=o.start.y+uy*length;}}
  $('#property-form').addEventListener('change',e=>{const o=getObject();if(!o)return;snapshot();const id=e.target.id,val=['number','range'].includes(e.target.type)?Number(e.target.value):e.target.value,linear=['glass','wall'].includes(selected.kind),isSpace=selected.kind==='space';
    if(id==='prop-name'&&o.name!=null)o.name=val;if(id==='prop-space'){if(isSpace)o.type=val;else o.space=val;}if(id==='prop-color')o.color=val;if(id==='prop-locked')o.locked=e.target.checked;if(id==='prop-door-direction')o.openingDirection=val;
    if(linear){if(id==='prop-x'){const dx=val-o.start.x;o.start.x+=dx;o.end.x+=dx}if(id==='prop-y'){const dy=val-o.start.y;o.start.y+=dy;o.end.y+=dy}if(id==='prop-w')setLineLength(o,val,$('#wall-anchor').value);if(id==='prop-h'&&selected.kind==='glass')o.thickness=Math.max(1,val);}
    else if(isSpace){if(id==='prop-x')o.bounds.x=val;if(id==='prop-y')o.bounds.y=val;if(id==='prop-w')o.bounds.w=Math.max(1,val);if(id==='prop-h')o.bounds.h=Math.max(1,val);}
    else if(selected.kind==='door'){if(id==='prop-x')o.x=val;if(id==='prop-y')o.y=val;if(id==='prop-w')o.width=Math.max(1,val);if(id==='prop-h')o.openingAngle=Math.max(10,Math.min(180,val));if(id==='prop-rotation')o.rotation=val;}
    else{if(id==='prop-x')o.x=val;if(id==='prop-y')o.y=val;if(id==='prop-w'&&o.w!=null)o.w=Math.max(1,val);if(id==='prop-h'&&o.h!=null)o.h=Math.max(1,val);if(id==='prop-rotation')o.rotation=val;}commit();});
  $('#prop-rotation').addEventListener('input',e=>{$('#rotation-value').textContent=`${e.target.value}°`;});
  $('#properties').addEventListener('click',e=>{const b=e.target.closest('[data-prop]');if(!b)return;const action=b.dataset.prop,o=getObject();if(action==='delete')deleteSelected();if(action==='duplicate')duplicateSelected();if(action==='rotate'&&o?.rotation!=null){snapshot();o.rotation=(o.rotation+90)%360;commit();}if(['horizontal','vertical'].includes(action)&&['wall','glass'].includes(selected?.kind)){snapshot();if(action==='horizontal')o.end.y=o.start.y;else o.end.x=o.start.x;commit(`${action==='horizontal'?'수평':'수직'}으로 정렬했습니다.`);}if(action==='split'&&['wall','glass'].includes(selected?.kind))splitSelectedLine();if(action==='merge')mergeSelectedWall();});
  function splitSelectedLine(){const o=getObject();if(!o)return;snapshot();if(selected.kind==='wall'){const m={id:uid('v'),x:(o.start.x+o.end.x)/2,y:(o.start.y+o.end.y)/2};state.roomBoundary.vertices.splice(selected.index+1,0,m);selected={kind:'wall',index:selected.index,id:`wall-${selected.index}`};}else{const m={x:(o.start.x+o.end.x)/2,y:(o.start.y+o.end.y)/2},copy={...clone(o),id:uid('glass'),start:clone(m)};o.end=clone(m);state.glassWalls.push(copy);selected={kind:'glass',id:copy.id};}commit('선분을 두 구간으로 나눴습니다.');}
  function mergeSelectedWall(){if(selected?.kind!=='wall')return showToast('일반 벽에서만 인접 벽을 병합할 수 있습니다.');if(state.roomBoundary.vertices.length<=3)return; snapshot();state.roomBoundary.vertices.splice((selected.index+1)%state.roomBoundary.vertices.length,1);selected=null;commit('인접 벽을 병합했습니다.');}
  function deleteSelected(){if(!selected)return;if(selected.kind==='multi'){snapshot();state.furniture=state.furniture.filter(x=>!selected.ids.includes(x.id));}else if(selected.kind==='vertex'||selected.kind==='wall'){if(state.roomBoundary.vertices.length<=3)return showToast('꼭짓점은 최소 3개가 필요합니다.');snapshot();state.roomBoundary.vertices.splice(selected.kind==='vertex'?selected.index:(selected.index+1)%state.roomBoundary.vertices.length,1);}else if(selected.kind==='furniture'){snapshot();state.furniture=state.furniture.filter(x=>x.id!==selected.id);}else if(selected.kind==='structure'){snapshot();state.structures=state.structures.filter(x=>x.id!==selected.id);}else if(selected.kind==='door'){snapshot();state.doors=state.doors.filter(x=>x.id!==selected.id);}else if(selected.kind==='glass'){if(state.glassWalls.length<=1)return showToast('기본 유리 파티션은 최소 한 구간을 유지합니다.');snapshot();state.glassWalls=state.glassWalls.filter(x=>x.id!==selected.id);}else return showToast('이 객체는 삭제할 수 없습니다.');selected=null;commit('선택한 객체를 삭제했습니다.');}
  function duplicateSelected(){const o=getObject();if(!o||!['furniture','structure','door'].includes(selected.kind))return showToast('이 객체는 복제할 수 없습니다.');snapshot();const copy={...clone(o),id:uid(o.type),name:`${o.name} 복사본`,x:o.x+state.gridSize,y:o.y+state.gridSize};const list=selected.kind==='furniture'?state.furniture:selected.kind==='structure'?state.structures:state.doors;list.push(copy);selected={kind:selected.kind,id:copy.id};commit('객체를 복제했습니다.');}

  function polygonArea(vs){let sum=0;for(let i=0;i<vs.length;i++){const a=vs[i],b=vs[(i+1)%vs.length];sum+=a.x*b.y-b.x*a.y;}return Math.abs(sum)/2;}
  function pointInPolygon(p,vs){let inside=false;for(let i=0,j=vs.length-1;i<vs.length;j=i++){const a=vs[i],b=vs[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x))inside=!inside;}return inside;}
  function rectCorners(o){const a=(o.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return[[-o.w/2,-o.h/2],[o.w/2,-o.h/2],[o.w/2,o.h/2],[-o.w/2,o.h/2]].map(([x,y])=>({x:o.x+x*c-y*s,y:o.y+x*s+y*c}));}
  function aabb(o){const c=rectCorners(o);return{l:Math.min(...c.map(p=>p.x)),r:Math.max(...c.map(p=>p.x)),t:Math.min(...c.map(p=>p.y)),b:Math.max(...c.map(p=>p.y))};}
  function overlap(a,b){const A=aabb(a),B=aabb(b);return A.l<B.r&&A.r>B.l&&A.t<B.b&&A.b>B.t;}
  function getWarnings(){const out=[],fs=state.furniture,vs=state.roomBoundary.vertices,minGlass=30;fs.forEach(o=>{if(rectCorners(o).some(p=>!pointInPolygon(p,vs)))out.push({text:`${o.name}이(가) 연구실 외곽선 밖으로 벗어났습니다.`,ids:[o.id]});state.doors.forEach(d=>{const zone={x:d.x+d.width/2,y:d.y-d.width/2,w:d.width,h:d.width,rotation:d.rotation||0};if(overlap(o,zone))out.push({text:`${o.name}이(가) ${d.name} 열림 영역을 침범하고 있습니다.`,ids:[o.id,d.id]});});state.glassWalls.forEach(g=>{const box=aabb(o),vertical=Math.abs(g.end.y-g.start.y)>Math.abs(g.end.x-g.start.x),radius=vertical?(box.r-box.l)/2:(box.b-box.t)/2,gap=pointSegmentDistance({x:o.x,y:o.y},g.start,g.end)-radius;if(gap<minGlass&&o.type!=='monitor')out.push({text:`${o.name}의 유리벽 안전거리가 ${Math.max(0,Math.round(gap))}cm로 기준 ${minGlass}cm보다 좁습니다.`,ids:[o.id,g.id]});});});for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++)if(overlap(fs[i],fs[j])){out.push({text:`${fs[i].name}과(와) ${fs[j].name}이(가) 서로 겹칩니다.`,ids:[fs[i].id,fs[j].id]});if((fs[i].type==='meetingTable'&&fs[j].type==='underDesk')||(fs[j].type==='meetingTable'&&fs[i].type==='underDesk'))out.push({text:'회의용 테이블과 학부생용 책상이 충돌하여 복합 공간 전환이 어렵습니다.',ids:[fs[i].id,fs[j].id]});}const fridge=fs.find(o=>o.type==='fridge');if(fridge){const access={x:fridge.x-100*Math.cos((fridge.rotation||0)*Math.PI/180),y:fridge.y-100*Math.sin((fridge.rotation||0)*Math.PI/180),w:120,h:100,rotation:fridge.rotation||0};const blocker=fs.find(o=>o.id!==fridge.id&&overlap(o,access));if(blocker)out.push({text:`${blocker.name}이(가) 냉장고 전면 접근 공간을 막고 있습니다.`,ids:[fridge.id,blocker.id]});}const monitor=fs.find(o=>o.type==='monitor');if(monitor){const front={x:monitor.x-100*Math.sin((monitor.rotation||0)*Math.PI/180),y:monitor.y+100*Math.cos((monitor.rotation||0)*Math.PI/180),w:monitor.w,h:180,rotation:monitor.rotation||0};const blocker=fs.find(o=>!['monitor','meetingTable','meetingChair'].includes(o.type)&&overlap(o,front));if(blocker)out.push({text:`${blocker.name}이(가) 대형 모니터 전면 시야를 가리고 있습니다.`,ids:[monitor.id,blocker.id]});}if(selfIntersects(vs))out.push({text:'연구실 외곽선이 자기 교차하여 저장할 수 없습니다.',ids:[]});return out;}
  function orient(a,b,c){return Math.sign((b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x));}
  function segmentsCross(a,b,c,d){return orient(a,b,c)!==orient(a,b,d)&&orient(c,d,a)!==orient(c,d,b);}
  function selfIntersects(vs){for(let i=0;i<vs.length;i++)for(let j=i+1;j<vs.length;j++){if(Math.abs(i-j)<=1||(i===0&&j===vs.length-1))continue;if(segmentsCross(vs[i],vs[(i+1)%vs.length],vs[j],vs[(j+1)%vs.length]))return true;}return false;}
  function targetSummary(){const counts={};state.furniture.forEach(o=>counts[o.type]=(counts[o.type]||0)+1);const entries=Object.entries(state.targetCounts||targetCounts),met=entries.reduce((n,[k,v])=>n+Math.min(counts[k]||0,v),0),total=entries.reduce((n,[,v])=>n+v,0);return{counts,entries,percent:total?Math.round(met/total*100):0};}
  function meetingMetrics(){const fs=state.furniture,m=fs.find(o=>o.type==='monitor'),t=fs.find(o=>o.type==='meetingTable'),chairs=fs.filter(o=>o.type==='meetingChair'),fridge=fs.find(o=>o.type==='fridge'),doorBlocked=getWarnings().some(w=>w.ids.some(id=>state.doors.some(d=>d.id===id)));return{distance:m&&t?Math.max(0,Math.round(distance(m,t)-Math.max(m.w,t.w)/2)):null,chairs:chairs.length,access:!doorBlocked,fridge:!!fridge};}
  function updateAnalysis(){const area=polygonArea(state.roomBoundary.vertices)/10000,occupied=state.furniture.reduce((s,o)=>s+o.w*o.h,0)/10000,seats=state.furniture.reduce((s,o)=>s+(o.seats||0),0),warnings=getWarnings(),targets=targetSummary();$('#stat-area').textContent=`${area.toFixed(1)} m²`;$('#stat-occupancy').textContent=`${area?Math.round(occupied/area*100):0}%`;$('#stat-seats').textContent=seats;$('#stat-warnings').textContent=warnings.length;$('#warning-count').textContent=warnings.length;$('#warning-list').innerHTML=warnings.length?warnings.map(w=>`<li class="warning-item">${escapeHtml(w.text)}</li>`).join(''):'<li class="all-clear"><span>✓</span>현재 배치에 문제가 없습니다.</li>';$('#target-percent').textContent=`${targets.percent}%`;$('#target-progress').value=targets.percent;$('#target-list').innerHTML=targets.entries.map(([k,goal])=>{const cur=targets.counts[k]||0,status=cur<goal?'under':cur===goal?'met':'over';return`<li class="${status}"><span>${escapeHtml(furnitureTypes[k]?.name||k)}</span><b>${cur} / ${goal}</b></li>`}).join('');const mm=meetingMetrics();$('#meeting-analysis').innerHTML=`<div class="meeting-metric"><span>모니터–테이블 거리</span><b>${mm.distance==null?'미배치':`${mm.distance} cm`}</b></div><div class="meeting-metric"><span>회의용 좌석</span><b>${mm.chairs}석</b></div><div class="meeting-metric"><span>출입구 접근</span><b>${mm.access?'확보':'차단'}</b></div><div class="meeting-metric"><span>냉장고</span><b>${mm.fridge?'배치됨':'미배치'}</b></div>`;updatePrintReport({area,occupied,seats,warnings,targets,mm});}
  function updatePrintReport(a){$('#print-meta').textContent=`${state.projectName} · ${new Date().toLocaleDateString('ko-KR')} · ${state.orientation.label} · 축척 ${$('#scale-label').textContent}`;$('#print-analysis').textContent=`전체 면적: ${a.area.toFixed(1)} m²\n가구 점유 면적: ${a.occupied.toFixed(1)} m²\n잔여 면적: ${(a.area-a.occupied).toFixed(1)} m²\n전체 좌석: ${a.seats}석\n회의 좌석: ${a.mm.chairs}석\n경고: ${a.warnings.length}건`;$('#print-targets').textContent=a.targets.entries.map(([k,g])=>`${furnitureTypes[k]?.name||k}: ${a.targets.counts[k]||0} / ${g}`).join('\n')+`\n전체 충족률: ${a.targets.percent}%`;$('#print-furniture').textContent=state.spaces.map(s=>`${s.name}: ${state.furniture.filter(o=>o.space===s.type).map(o=>o.name).join(', ')||'없음'}`).join('\n\n');$('#print-warnings').textContent=a.warnings.length?a.warnings.map((w,i)=>`${i+1}. ${w.text}`).join('\n'):'경고 없음';}
  function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

  $('[data-action="undo"]').addEventListener('click',undo);$('[data-action="redo"]').addEventListener('click',redo);
  $('[data-action="new"]').addEventListener('click',()=>{if(!confirm('현재 작업을 지우고 새 도면을 시작할까요?'))return;snapshot();state=initial();buildLayout('flex');state.initialized=true;selected=null;commit('새 추천 배치안으로 시작했습니다.');fitView();});
  $('[data-action="save"]').addEventListener('click',saveNow);
  function saveNow(){if(selfIntersects(state.roomBoundary.vertices))return showToast('자기 교차 외곽선은 저장할 수 없습니다.');try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));showToast('현재 배치안을 저장했습니다.');}catch(e){showToast('저장 공간이 부족합니다.');}}
  function rotateProject(degrees){snapshot();rotateData(state,degrees,true);state.orientation.rotationDegrees=((state.orientation.rotationDegrees+degrees+540)%360)-180;state.orientation.label=state.orientation.rotationDegrees===-90?'왼쪽으로 90도 회전':`${state.orientation.rotationDegrees}도 회전`;selected=null;commit(`${degrees<0?'왼쪽':'오른쪽'}으로 90도 회전했습니다.`);fitView();}
  $('[data-action="rotate-left"]').addEventListener('click',()=>rotateProject(-90));$('[data-action="rotate-right"]').addEventListener('click',()=>rotateProject(90));
  $('[data-action="export-json"]').addEventListener('click',()=>{if(selfIntersects(state.roomBoundary.vertices))return showToast('자기 교차 외곽선은 내보낼 수 없습니다.');download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'aiad-layout-v2.json');});
  $('[data-action="import-json"]').addEventListener('click',()=>$('#json-file').click());
  $('#json-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{let data=JSON.parse(await f.text());if(!data.roomBoundary?.vertices?.length)throw new Error();snapshot();if(!data.orientation){localStorage.setItem(`aiad-import-backup-${Date.now()}`,JSON.stringify(data));const rotate=confirm('구버전 JSON입니다. 세로형 도면을 왼쪽으로 90도 회전하여 가져올까요?');data=migrateLegacy(data,rotate);}else data=normalizeV2(data);state=data;selected=null;commit('배치안을 불러왔습니다.');fitView();}catch(err){showToast('지원하지 않거나 손상된 JSON 파일입니다.');}e.target.value='';});
  $('[data-action="png"]').addEventListener('click',()=>{const scale=Number(prompt('PNG 해상도 배율을 입력하세요 (1, 2, 4)','2'));if(![1,2,4].includes(scale))return showToast('해상도는 1, 2, 4 중에서 선택하세요.');const includeGrid=confirm('PNG에 배경 격자를 포함할까요?'),oldSel=selected,oldGrid=state.settings.showGrid;selected=null;state.settings.showGrid=includeGrid;render();const out=document.createElement('canvas');out.width=canvas.width*scale;out.height=canvas.height*scale;out.getContext('2d').drawImage(canvas,0,0,out.width,out.height);out.toBlob(b=>download(b,`aiad-layout-${scale}x.png`));selected=oldSel;state.settings.showGrid=oldGrid;render();});
  $('[data-action="print"]').addEventListener('click',()=>window.print());
  const dialog=$('#help-dialog');$('[data-action="help"]').addEventListener('click',()=>dialog.showModal());$('#help-dialog .dialog-close').addEventListener('click',()=>dialog.close());$('.compare-close').addEventListener('click',()=>$('#compare-dialog').close());
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  $('#grid-size').value=String(state.gridSize||50);$('#grid-size').addEventListener('change',e=>{snapshot();state.gridSize=Number(e.target.value);$('#grid-label').textContent=`${state.gridSize} cm`;commit();});
  $('#unit').value=state.unit||'cm';$('#unit').addEventListener('change',e=>{state.unit=e.target.value;showToast(`표시 단위를 ${state.unit}(으)로 변경했습니다.`);});
  $('#snap').checked=state.settings.snap!==false;$('#snap').addEventListener('change',e=>{state.settings.snap=e.target.checked;commit();});
  $('#object-snap').checked=state.settings.objectSnap!==false;$('#object-snap').addEventListener('change',e=>{state.settings.objectSnap=e.target.checked;commit();});
  $('#grid-toggle').classList.toggle('active',state.settings.showGrid!==false);$('#grid-toggle').addEventListener('click',e=>{state.settings.showGrid=!state.settings.showGrid;e.currentTarget.classList.toggle('active',state.settings.showGrid);render();});
  $('#dimension-toggle').classList.toggle('active',state.settings.showDimensions!==false);$('#dimension-toggle').addEventListener('click',e=>{state.settings.showDimensions=!state.settings.showDimensions;e.currentTarget.classList.toggle('active',state.settings.showDimensions);render();});
  $('#fit').addEventListener('click',fitView);$('#focus-selected').addEventListener('click',()=>{const o=getObject();if(!o||o.x==null)return showToast('중심에 맞출 객체를 선택하세요.');view.panX=wrap.clientWidth/2-o.x*view.zoom;view.panY=wrap.clientHeight/2-o.y*view.zoom;render();});$('#zoom-in').addEventListener('click',()=>setZoom(view.zoom*1.2));$('#zoom-out').addEventListener('click',()=>setZoom(view.zoom/1.2));
  window.addEventListener('keydown',e=>{const tag=document.activeElement.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(e.code==='Space'){spaceDown=true;e.preventDefault();}if(e.key==='Delete')deleteSelected();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveNow();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selected={kind:'multi',ids:state.furniture.map(o=>o.id)};showToast(`가구 ${selected.ids.length}개를 선택했습니다.`);render();}const map={v:'select',n:'vertices',w:'walls',m:'measure',h:'pan'};if(map[e.key.toLowerCase()])setTool(map[e.key.toLowerCase()]);if(e.key==='Escape'){selected=null;measurePoints=[];updateProperties();render();}});
  window.addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false;});
  new ResizeObserver(resize).observe(wrap);
  function runSelfTests(){const tests=[],check=(name,pass)=>tests.push({name,pass:!!pass});const counts=targetSummary().counts,g=state.glassWalls[0];check('v2 orientation',state.version==='2.0.0'&&state.orientation.rotationDegrees===-90);check('vertical glass partition',g.start.x===g.end.x&&g.start.y!==g.end.y);check('bottom door',state.doors[0].y===Math.max(...state.roomBoundary.vertices.map(v=>v.y)));check('editable polygon',state.roomBoundary.vertices.length>=3&&!selfIntersects(state.roomBoundary.vertices));check('graduate desks 6',counts.gradDesk===6);check('undergraduate desks 4',counts.underDesk===4);check('small professor desks 2',counts.profSmall===2);check('large professor desk 1',counts.profLarge===1);check('target fulfillment 100%',targetSummary().percent===100);check('recommended layout collision free',getWarnings().length===0);check('JSON round trip',JSON.parse(JSON.stringify(state)).orientation.rotationDegrees===-90);const migrated=migrateLegacy({version:'1.0.0',roomBoundary:{vertices:[{id:'a',x:0,y:0},{id:'b',x:100,y:0},{id:'c',x:100,y:200},{id:'d',x:0,y:200}]},glassWall:{id:'g',start:{x:0,y:100},end:{x:100,y:100},thickness:10},doors:[],structures:[],furniture:[],settings:{}},true);check('legacy v1 migration',migrated.version==='2.0.0'&&migrated.orientation.rotationDegrees===-90&&migrated.glassWalls[0].start.x===migrated.glassWalls[0].end.x);const result=document.createElement('pre');result.id='self-test-results';result.textContent=JSON.stringify({passed:tests.filter(t=>t.pass).length,total:tests.length,tests},null,2);document.body.appendChild(result);}
  if(!state.initialized){buildLayout('flex');state.initialized=true;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}$('#grid-label').textContent=`${state.gridSize} cm`;$$('[data-layout]').forEach(b=>b.classList.toggle('active',b.dataset.layout===state.activeLayout));updateAnalysis();updateProperties();resize();requestAnimationFrame(fitView);if(new URLSearchParams(location.search).has('selftest'))runSelfTests();
})();
