(() => {
  'use strict';

  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const canvas = $('#plan');
  const ctx = canvas.getContext('2d');
  const wrap = $('#canvas-wrap');
  const STORAGE_KEY = 'aiad-lab-layout-v2';
  const LEGACY_STORAGE_KEY = 'aiad-lab-layout-v1';
  const DRAFT_STORAGE_KEY = 'aiad-lab-draft-v3';
  const palette = { wall:'#465167', glass:'#42b8d8', blue:'#3276e8', red:'#db4b52', green:'#2e9d74', ink:'#182238', muted:'#738097' };

  const official = window.AIAD_DEFAULT_FLOORPLAN;
  const initial = () => ({
    version:'3.1.0', officialRevision:official.revision, projectName:'빈 연구실', activeLayout:'empty', unit:'cm', gridSize:20,
    orientation:{rotationDegrees:0,label:'실측 도면 방향'},
    room:{boundary:clone(official.boundary),walls:clone(official.walls),glassWalls:clone(official.glassWalls),doors:clone(official.doors),windows:clone(official.windows),fixedFacilities:clone(official.fixedFacilities)},
    roomBoundary:{type:'polygon',closed:true,locked:true,vertices:clone(official.boundary)},
    spaces:[{id:'space-main',name:'AIAD 연구실',type:'common',bounds:{x:0,y:0,w:624,h:800}},{id:'space-east',name:'회의·학습 공간',type:'undergrad',bounds:{x:624,y:169,w:541,h:631}}],
    walls:clone(official.walls),glassWalls:clone(official.glassWalls),doors:clone(official.doors),windows:clone(official.windows),structures:clone(official.fixedFacilities),dimensions:clone(official.dimensions),
    furniture:[],layouts:{},initialized:true,
    settings:{snap:true,objectSnap:true,zoom:1,showGrid:true,showDimensions:true,wallThickness:12,wallHeight:official.wallHeight,minAisleWidth:80},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()
  });
  let state = initial();
  let view = {zoom:1, panX:0, panY:0};
  let tool = 'select', selected = null, dragging = null, hovered = null, measurePoints = [], spaceDown = false, altDown = false, selectionRect = null, snapGuides = [], viewMode = '2d';
  let history = [], future = [], saveTimer, toastTimer, renderWarnings=[];
  let sceneManager = null;

  const furnitureTypes = {
    desk:{name:'책상',w:140,h:70,color:'#79a8d8',seats:0,space:'workspace'},existingDesk:{name:'기존 책상',w:180,h:100,color:'#5f7f9f',seats:0,space:'workspace',numbered:false},chair:{name:'의자',w:60,h:60,color:'#69b394',seats:1,space:'workspace'},
    monitor:{name:'대형 모니터',w:160,h:20,color:'#459bb5',seats:0,space:'meeting'},meetingTable:{name:'회의용 테이블',w:180,h:90,color:'#d99a55',seats:0,space:'meeting'},meetingChair:{name:'회의용 의자',w:60,h:60,color:'#d9b16f',seats:1,space:'meeting'},
    sofa:{name:'소파',w:240,h:80,color:'#c7839f',seats:3,space:'meeting',numbered:false},fridge:{name:'냉장고',w:48,h:52,color:'#83a9bc',seats:0,space:'common',numbered:false},
    cabinet:{name:'캐비닛',w:90,h:45,color:'#8793a7',seats:0,space:'common'},shelf:{name:'책장',w:120,h:40,color:'#b98c68',seats:0,space:'common'},printer:{name:'프린터',w:60,h:60,color:'#9d826c',seats:0,space:'common'},whiteboard:{name:'이동식 화이트보드',w:140,h:20,color:'#7596a7',seats:0,space:'common'},custom:{name:'사용자 정의 가구',w:100,h:100,color:'#8b93a5',seats:0,space:'custom'}
  };

  function uid(prefix){ return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`; }
  function clone(v){ return JSON.parse(JSON.stringify(v)); }
  function snapshot(){ history.push(clone(state)); if(history.length>50) history.shift(); future=[]; }
  function commit(message){ state.updatedAt=new Date().toISOString();state.room={boundary:state.roomBoundary.vertices,walls:state.walls,glassWalls:state.glassWalls,doors:state.doors,windows:state.windows,fixedFacilities:state.structures};$('#project-label').textContent=state.projectName; clearTimeout(saveTimer); saveTimer=setTimeout(backupDraft,350); updateAnalysis(); updateProperties(); render(); if(viewMode==='3d')sceneManager?.build(state); window.AIADProjectManager?.onLocalChange(); if(message) showToast(message); }
  function readLegacyProject(){
    try{
      const raw=localStorage.getItem(STORAGE_KEY);if(raw)return normalizeV2(JSON.parse(raw));
      const legacy=localStorage.getItem(LEGACY_STORAGE_KEY);if(!legacy)return null;
      return migrateLegacy(JSON.parse(legacy),true);
    }catch(e){return null;}
  }
  function backupDraft(){try{localStorage.setItem(DRAFT_STORAGE_KEY,JSON.stringify(serializeProject()));}catch(e){showToast('임시 백업 공간이 부족합니다.');}}
  function serializeProject(){const data=clone(state);data.layouts={};return data;}
  function normalizeV2(data){
    const base=initial(),wasLegacyOfficial=data.officialRevision!==official.revision;data.version='3.1.0';data.orientation=data.orientation||base.orientation;data.spaces=data.spaces||base.spaces;data.glassWalls=data.glassWalls||(data.glassWall?[data.glassWall]:base.glassWalls);delete data.glassWall;data.walls=data.walls||[];data.windows=data.windows||[];data.doors=data.doors||base.doors;data.structures=data.structures||[];data.furniture=data.furniture||[];data.layouts=data.layouts||{};data.settings={...base.settings,...data.settings};delete data.targetCounts;
    const typeMap={graduateDesk:'desk',undergraduateDesk:'desk',professorLargeDesk:'desk',professorSmallDesk:'desk',gradDesk:'desk',underDesk:'desk',profLarge:'desk',profSmall:'desk',desk2:'desk',graduateChair:'chair',undergraduateChair:'chair',gradChair:'chair',underChair:'chair'};data.furniture.forEach(o=>{o.type=typeMap[o.type]||o.type;if(o.type==='desk')o.name=(o.name||'책상').replace(/대학원생용|학부생용|교수님용|큰 |작은 /g,'').trim()||'책상';if(o.type==='chair')o.name=(o.name||'의자').replace(/대학원생용|학부생용/g,'').trim()||'의자';if(['graduate','undergrad','undergraduate','professor'].includes(o.space))o.space='workspace';});Object.keys(data.layouts).forEach(name=>data.layouts[name]=(data.layouts[name]||[]).map(o=>{o.type=typeMap[o.type]||o.type;if(['graduate','undergrad','undergraduate','professor'].includes(o.space))o.space='workspace';return o;}));
    if(wasLegacyOfficial){data.officialRevision=official.revision;data.roomBoundary=clone(base.roomBoundary);data.walls=clone(base.walls);data.glassWalls=clone(base.glassWalls);data.doors=clone(base.doors);data.windows=clone(base.windows);data.structures=clone(base.structures);data.dimensions=clone(base.dimensions);data.spaces=clone(base.spaces);}
    data.room={boundary:data.roomBoundary.vertices,walls:data.walls,glassWalls:data.glassWalls,doors:data.doors,windows:data.windows,fixedFacilities:data.structures};data.initialized=true;return data;
  }
  function migrateLegacy(old,rotate=true){
    const data=clone(old);if(rotate)rotateData(data,-90,false);data.version='3.1.0';data.orientation={rotationDegrees:rotate?-90:0,label:rotate?'왼쪽으로 90도 회전':'기존 방향'};data.glassWalls=data.glassWalls||(data.glassWall?[data.glassWall]:[]);delete data.glassWall;
    const typeMap={desk:'desk',desk2:'desk',table:'meetingTable',graduateDesk:'desk',undergraduateDesk:'desk',professorLargeDesk:'desk',professorSmallDesk:'desk',graduateChair:'chair',undergraduateChair:'chair',gradDesk:'desk',underDesk:'desk',profLarge:'desk',profSmall:'desk',gradChair:'chair',underChair:'chair'};(data.furniture||[]).forEach(o=>{o.type=typeMap[o.type]||o.type;o.space='workspace';});delete data.targetCounts;return normalizeV2(data);
  }
  function rotatePoint(p,degrees){const rad=degrees*Math.PI/180,c=Math.cos(rad),s=Math.sin(rad);return{x:p.x*c-p.y*s,y:p.x*s+p.y*c};}
  function rotateData(data,degrees,normalize=true){
    const refs=[];(data.roomBoundary?.vertices||[]).forEach(p=>refs.push(p));(data.glassWalls||(data.glassWall?[data.glassWall]:[])).forEach(g=>{refs.push(g.start,g.end)});(data.doors||[]).forEach(ref=>refs.push(ref));(data.windows||[]).forEach(ref=>refs.push(ref));(data.structures||[]).forEach(ref=>refs.push(ref));(data.furniture||[]).forEach(ref=>refs.push(ref));
    const rotated=refs.map(p=>rotatePoint(p,degrees)),minX=normalize?Math.min(...rotated.map(p=>p.x)):0,minY=normalize?Math.min(...rotated.map(p=>p.y)):0;refs.forEach((p,i)=>{p.x=Math.round(rotated[i].x-minX);p.y=Math.round(rotated[i].y-minY);if(p.rotation!=null)p.rotation=(p.rotation+degrees+360)%360;});
    (data.spaces||[]).forEach(s=>{const corners=[{x:s.bounds.x,y:s.bounds.y},{x:s.bounds.x+s.bounds.w,y:s.bounds.y+s.bounds.h}].map(p=>rotatePoint(p,degrees));s.bounds={x:Math.min(...corners.map(p=>p.x))-minX,y:Math.min(...corners.map(p=>p.y))-minY,w:Math.abs(corners[1].x-corners[0].x),h:Math.abs(corners[1].y-corners[0].y)};});
  }
  function undo(){ if(!history.length)return showToast('되돌릴 작업이 없습니다.');future.push(clone(state));state=history.pop();selected=null;commit(); }
  function redo(){ if(!future.length)return showToast('다시 실행할 작업이 없습니다.');history.push(clone(state));state=future.pop();selected=null;commit(); }
  function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800);}
  function snap(v){return state.settings.snap?Math.round(v/state.gridSize)*state.gridSize:v;}
  function worldToScreen(p){return{x:p.x*view.zoom+view.panX,y:p.y*view.zoom+view.panY};}
  function screenToWorld(p){return{x:(p.x-view.panX)/view.zoom,y:(p.y-view.panY)/view.zoom};}
  function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}

  function resize(){const r=wrap.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);render();}
  function fitView(){const r=wrap.getBoundingClientRect(),vs=state.roomBoundary.vertices;const minX=Math.min(...vs.map(v=>v.x)),maxX=Math.max(...vs.map(v=>v.x)),minY=Math.min(...vs.map(v=>v.y)),maxY=Math.max(...vs.map(v=>v.y));view.zoom=Math.min((r.width-150)/(maxX-minX),(r.height-100)/(maxY-minY));view.zoom=Math.max(.25,Math.min(2,view.zoom));view.panX=(r.width-(maxX-minX)*view.zoom)/2-minX*view.zoom;view.panY=(r.height-(maxY-minY)*view.zoom)/2-minY*view.zoom;updateZoom();render();}
  function updateZoom(){$('#zoom-label').textContent=`${Math.round(view.zoom*100)}%`;$('#scale-label').textContent=`1:${Math.max(10,Math.round(50/view.zoom/10)*10)}`;}
  function setZoom(z,center){const old=view.zoom;z=Math.max(.25,Math.min(4,z));center=center||{x:wrap.clientWidth/2,y:wrap.clientHeight/2};const wx=(center.x-view.panX)/old,wy=(center.y-view.panY)/old;view.zoom=z;view.panX=center.x-wx*z;view.panY=center.y-wy*z;updateZoom();render();}

  function render(){
    const w=wrap.clientWidth,h=wrap.clientHeight;renderWarnings=getWarnings();ctx.clearRect(0,0,w,h);drawGrid(w,h);
    ctx.save();ctx.translate(view.panX,view.panY);ctx.scale(view.zoom,view.zoom);
    drawRoom();drawSpaces();(state.walls||[]).forEach(drawInternalWall);(state.windows||[]).forEach(drawWindow);state.glassWalls.forEach(drawGlass);state.structures.forEach(drawStructure);state.doors.forEach(drawDoor);state.furniture.forEach(drawFurniture);drawMeasurements();drawDimensions();drawSnapGuides();drawSelectionRect();ctx.restore();
  }
  function drawGrid(w,h){if(!state.settings.showGrid)return;const step=Math.max(12,state.gridSize*view.zoom);ctx.save();ctx.strokeStyle='#d7dde6';ctx.lineWidth=1;ctx.globalAlpha=.65;const ox=((view.panX%step)+step)%step,oy=((view.panY%step)+step)%step;ctx.beginPath();for(let x=ox;x<w;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let y=oy;y<h;y+=step){ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();ctx.restore();}
  function pathRoom(){const vs=state.roomBoundary.vertices;ctx.beginPath();vs.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.closePath();}
  function drawRoom(){const invalid=selfIntersects(state.roomBoundary.vertices);pathRoom();ctx.fillStyle=invalid?'rgba(219,75,82,.06)':'rgba(255,255,255,.82)';ctx.fill();ctx.strokeStyle=invalid?palette.red:palette.wall;ctx.lineWidth=8/view.zoom;ctx.lineJoin='round';ctx.stroke();
    if(tool==='vertices'){state.roomBoundary.vertices.forEach((v,i)=>{ctx.beginPath();ctx.arc(v.x,v.y,7/view.zoom,0,Math.PI*2);ctx.fillStyle=selected?.kind==='vertex'&&selected.index===i?'#3276e8':'#fff';ctx.fill();ctx.strokeStyle='#3276e8';ctx.lineWidth=2/view.zoom;ctx.stroke();});}
    if(tool==='walls'||selected?.kind==='wall'){const vs=state.roomBoundary.vertices;vs.forEach((v,i)=>{const n=vs[(i+1)%vs.length],active=selected?.kind==='wall'&&selected.index===i;ctx.beginPath();ctx.moveTo(v.x,v.y);ctx.lineTo(n.x,n.y);ctx.strokeStyle=active?palette.blue:'rgba(50,118,232,.45)';ctx.lineWidth=(active?7:3)/view.zoom;ctx.stroke();if(state.settings.showDimensions){const m={x:(v.x+n.x)/2,y:(v.y+n.y)/2};ctx.fillStyle=palette.ink;ctx.font=`${10/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillText(`${Math.round(distance(v,n))} cm`,m.x,m.y-9/view.zoom);}});}
    if(invalid){const p=state.roomBoundary.vertices[0];ctx.fillStyle=palette.red;ctx.font=`${12/view.zoom}px sans-serif`;ctx.fillText('외곽선이 교차합니다',p.x,p.y-18/view.zoom);}
  }
  function drawSpaces(){ctx.save();pathRoom();ctx.clip();state.spaces.forEach(s=>{const b=s.bounds;ctx.fillStyle=s.type==='undergrad'?'rgba(129,93,205,.025)':'rgba(243,169,59,.025)';ctx.fillRect(b.x,b.y,b.w,b.h);});ctx.restore();}
  function drawGlass(g){ctx.save();ctx.globalAlpha=g.opacity??.72;ctx.strokeStyle='rgba(76,201,232,.28)';ctx.lineWidth=Math.max(g.thickness,16/view.zoom);ctx.beginPath();ctx.moveTo(g.start.x,g.start.y);ctx.lineTo(g.end.x,g.end.y);ctx.stroke();ctx.strokeStyle=palette.glass;ctx.lineWidth=3/view.zoom;ctx.setLineDash([12/view.zoom,7/view.zoom]);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.save();ctx.translate((g.start.x+g.end.x)/2,(g.start.y+g.end.y)/2);ctx.fillStyle=palette.muted;ctx.font=`${11/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillText('유리 파티션',0,-10/view.zoom);ctx.restore();if(selected?.kind==='glass'&&selected.id===g.id){[g.start,g.end].forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,7/view.zoom,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=palette.blue;ctx.lineWidth=2/view.zoom;ctx.stroke();});}ctx.restore();}
  function drawInternalWall(w){const a=w.start||w.startPoint,b=w.end||w.endPoint;ctx.save();ctx.strokeStyle=palette.wall;ctx.lineWidth=(w.thickness||12);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore();}
  function drawWindow(w){const a=w.start||w.startPoint,b=w.end||w.endPoint;ctx.save();ctx.strokeStyle='#4da6d8';ctx.lineWidth=8/view.zoom;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=2/view.zoom;ctx.stroke();ctx.restore();}
  function drawDoor(d){ctx.save();const warning=renderWarnings.some(w=>w.ids.includes(d.id)),down=(d.openingDirection||'').includes('down'),right=(d.openingDirection||'').includes('right'),sign=down?1:-1,hinge=right?d.width:0;ctx.translate(d.x,d.y);ctx.rotate((d.rotation||0)*Math.PI/180);ctx.strokeStyle=warning?palette.red:palette.green;ctx.lineWidth=3/view.zoom;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(d.width,0);ctx.stroke();ctx.beginPath();ctx.arc(hinge,0,d.width,right?Math.PI:sign*Math.PI/2,right?Math.PI+sign*Math.PI/2:0,sign<0);ctx.strokeStyle=warning?palette.red:'rgba(46,157,116,.65)';ctx.lineWidth=2/view.zoom;ctx.stroke();ctx.beginPath();ctx.moveTo(hinge,0);ctx.lineTo(hinge,sign*d.width);ctx.stroke();if(selected?.kind==='door'&&selected.id===d.id){ctx.beginPath();ctx.arc(hinge,0,7/view.zoom,0,Math.PI*2);ctx.fillStyle=palette.blue;ctx.fill();}ctx.restore();}
  function drawStructure(o){const w=o.w||o.width,h=o.h||o.height,point=['outlet','lan'].includes(o.type),symbolOnly=point||o.type==='distribution';ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.fillStyle=o.type==='column'?'#526077':o.type==='outlet'?'#2f74d0':o.type==='lan'?'#d83b45':o.type==='distribution'?'#fff4b8':'#cad3de';if(point){ctx.beginPath();ctx.arc(0,0,Math.max(5/view.zoom,4),0,Math.PI*2);ctx.fill();}else{ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeStyle=o.type==='distribution'?'#d1a62d':selected?.id===o.id?palette.blue:'#7d8999';ctx.lineWidth=(selected?.id===o.id?3:1.5)/view.zoom;ctx.strokeRect(-w/2,-h/2,w,h);}if(!symbolOnly){ctx.fillStyle=o.type==='column'?'#fff':palette.ink;ctx.textAlign='left';ctx.textBaseline='middle';ctx.font=`${10/view.zoom}px sans-serif`;ctx.fillText(o.label||o.name,-w/2+4/view.zoom,0);}ctx.restore();}
  function drawFurniture(o){const warning=renderWarnings.some(w=>w.ids.includes(o.id)),isSelected=selected?.id===o.id||(selected?.kind==='multi'&&selected.ids.includes(o.id)),angle=(o.rotation||0)*Math.PI/180;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(angle);ctx.fillStyle=o.color;ctx.globalAlpha=o.opacity??.88;roundRect(ctx,-o.w/2,-o.h/2,o.w,o.h,Math.min(8,o.h/4));ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=warning?palette.red:isSelected?palette.blue:'rgba(33,48,73,.42)';ctx.lineWidth=(warning||isSelected?3:1.5)/view.zoom;ctx.stroke();if(isSelected&&selected.kind!=='multi'){ctx.beginPath();ctx.arc(0,-o.h/2-18/view.zoom,6/view.zoom,0,Math.PI*2);ctx.fillStyle=palette.blue;ctx.fill();ctx.beginPath();ctx.moveTo(0,-o.h/2);ctx.lineTo(0,-o.h/2-12/view.zoom);ctx.strokeStyle=palette.blue;ctx.lineWidth=2/view.zoom;ctx.stroke();ctx.fillStyle='#fff';ctx.fillRect(o.w/2-5/view.zoom,o.h/2-5/view.zoom,10/view.zoom,10/view.zoom);ctx.strokeRect(o.w/2-5/view.zoom,o.h/2-5/view.zoom,10/view.zoom,10/view.zoom);}ctx.rotate(-angle);ctx.fillStyle='#24344f';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.max(10,12/view.zoom)}px sans-serif`;ctx.fillText(o.name,0,0);if(o.locked){ctx.fillStyle=palette.ink;ctx.font=`${12/view.zoom}px sans-serif`;ctx.fillText('🔒',Math.min(o.w,o.h)/2-10/view.zoom,-Math.min(o.w,o.h)/2+10/view.zoom);}ctx.restore();if(altDown&&selected?.id===o.id)drawNearbyDistances(o);}
  function drawNearbyDistances(o){const peers=state.furniture.filter(x=>x.id!==o.id).sort((a,b)=>distance(o,a)-distance(o,b)).slice(0,2);peers.forEach(p=>{const d=Math.max(0,Math.round(distance(o,p)-(Math.max(o.w,o.h)+Math.max(p.w,p.h))/2));ctx.save();ctx.strokeStyle='#8c55d9';ctx.fillStyle='#663bb0';ctx.lineWidth=1/view.zoom;ctx.setLineDash([4/view.zoom,3/view.zoom]);ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.setLineDash([]);ctx.font=`${10/view.zoom}px sans-serif`;ctx.fillText(`${d} cm`,(o.x+p.x)/2,(o.y+p.y)/2-5/view.zoom);ctx.restore();});}
  function localPoint(p,o){const a=-(o.rotation||0)*Math.PI/180,dx=p.x-o.x,dy=p.y-o.y;return{x:dx*Math.cos(a)-dy*Math.sin(a),y:dx*Math.sin(a)+dy*Math.cos(a)};}
  function selectedHandle(p){if(selected?.kind!=='furniture')return null;const o=getObject(),q=localPoint(p,o),tol=12/view.zoom;if(distance(q,{x:0,y:-o.h/2-18/view.zoom})<tol)return'rotate';if(distance(q,{x:o.w/2,y:o.h/2})<tol)return'resize';return null;}
  function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect?c.roundRect(x,y,w,h,r):(c.rect(x,y,w,h));}
  function drawMeasurements(){if(!measurePoints.length)return;ctx.save();ctx.strokeStyle=palette.blue;ctx.fillStyle=palette.blue;ctx.lineWidth=2/view.zoom;ctx.setLineDash([7/view.zoom,5/view.zoom]);ctx.beginPath();ctx.moveTo(measurePoints[0].x,measurePoints[0].y);if(measurePoints[1])ctx.lineTo(measurePoints[1].x,measurePoints[1].y);ctx.stroke();measurePoints.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,5/view.zoom,0,Math.PI*2);ctx.fill();});if(measurePoints[1]){const d=distance(measurePoints[0],measurePoints[1]),m={x:(measurePoints[0].x+measurePoints[1].x)/2,y:(measurePoints[0].y+measurePoints[1].y)/2};ctx.setLineDash([]);ctx.font=`${12/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillStyle=palette.ink;ctx.fillText(`${Math.round(d)} cm · ${(d/100).toFixed(2)} m`,m.x,m.y-10/view.zoom);}ctx.restore();}
  function drawDimensions(){if(!state.settings.showDimensions)return;(state.dimensions||[]).forEach(d=>{const a=d.startPoint,b=d.endPoint;ctx.save();ctx.strokeStyle='#8793a5';ctx.fillStyle='#536077';ctx.lineWidth=1/view.zoom;ctx.setLineDash([4/view.zoom,3/view.zoom]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);ctx.font=`${11/view.zoom}px sans-serif`;ctx.textAlign='center';ctx.fillText(d.label,(a.x+b.x)/2,(a.y+b.y)/2-6/view.zoom);ctx.restore();});}
  function drawSelectionRect(){if(!selectionRect)return;const x=Math.min(selectionRect.start.x,selectionRect.end.x),y=Math.min(selectionRect.start.y,selectionRect.end.y),w=Math.abs(selectionRect.end.x-selectionRect.start.x),h=Math.abs(selectionRect.end.y-selectionRect.start.y);ctx.save();ctx.fillStyle='rgba(39,107,232,.10)';ctx.strokeStyle=palette.blue;ctx.lineWidth=1.5/view.zoom;ctx.setLineDash([5/view.zoom,4/view.zoom]);ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.restore();}
  function drawSnapGuides(){snapGuides.forEach(g=>{ctx.save();ctx.strokeStyle='#d04dd8';ctx.lineWidth=1/view.zoom;ctx.setLineDash([5/view.zoom,4/view.zoom]);ctx.beginPath();ctx.moveTo(g.x1,g.y1);ctx.lineTo(g.x2,g.y2);ctx.stroke();if(g.label){ctx.fillStyle='#a233aa';ctx.font=`${10/view.zoom}px sans-serif`;ctx.fillText(g.label,(g.x1+g.x2)/2,(g.y1+g.y2)/2-5/view.zoom);}ctx.restore();});}

  function findAt(p){
    for(let i=state.furniture.length-1;i>=0;i--){const o=state.furniture[i];if(inRotatedRect(p,o))return{kind:'furniture',id:o.id};}
    if(['vertices','walls'].includes(tool)){for(let i=state.structures.length-1;i>=0;i--){const o=state.structures[i];if(inRotatedRect(p,o))return{kind:'structure',id:o.id};}for(let i=state.doors.length-1;i>=0;i--){const d=state.doors[i];if(distance(p,d)<Math.max(18,d.width/3))return{kind:'door',id:d.id};}}
    if(tool==='vertices'){const i=state.roomBoundary.vertices.findIndex(v=>distance(p,v)<12/view.zoom);if(i>=0)return{kind:'vertex',index:i,id:state.roomBoundary.vertices[i].id};}
    if(tool==='walls'){const vs=state.roomBoundary.vertices;let best={index:-1,d:Infinity};vs.forEach((v,i)=>{const d=pointSegmentDistance(p,v,vs[(i+1)%vs.length]);if(d<best.d)best={index:i,d};});if(best.d<15/view.zoom)return{kind:'wall',index:best.index,id:`wall-${best.index}`};}
    for(const g of state.glassWalls){if(distance(p,g.start)<12/view.zoom)return{kind:'glass',id:g.id,endpoint:'start'};if(distance(p,g.end)<12/view.zoom)return{kind:'glass',id:g.id,endpoint:'end'};if(pointSegmentDistance(p,g.start,g.end)<12/view.zoom)return{kind:'glass',id:g.id};}
    for(const s of state.spaces){const b=s.bounds;if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h&&pointInPolygon(p,state.roomBoundary.vertices))return{kind:'space',id:s.id};}
    return null;
  }
  function getObject(sel=selected){if(!sel)return null;if(sel.kind==='furniture')return state.furniture.find(x=>x.id===sel.id);if(sel.kind==='structure')return state.structures.find(x=>x.id===sel.id);if(sel.kind==='door')return state.doors.find(x=>x.id===sel.id);if(sel.kind==='space')return state.spaces.find(x=>x.id===sel.id);if(sel.kind==='glass')return state.glassWalls.find(x=>x.id===sel.id);if(sel.kind==='vertex')return state.roomBoundary.vertices[sel.index];if(sel.kind==='wall'){const a=state.roomBoundary.vertices[sel.index],b=state.roomBoundary.vertices[(sel.index+1)%state.roomBoundary.vertices.length];return{type:'wall',name:`벽 ${sel.index+1}`,start:a,end:b,thickness:state.settings.wallThickness};}return null;}
  function inRotatedRect(p,o){const a=-(o.rotation||0)*Math.PI/180,dx=p.x-o.x,dy=p.y-o.y,x=dx*Math.cos(a)-dy*Math.sin(a),y=dx*Math.sin(a)+dy*Math.cos(a);return Math.abs(x)<=o.w/2&&Math.abs(y)<=o.h/2;}
  function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
  function pointSegmentDistance(p,a,b){const l2=(b.x-a.x)**2+(b.y-a.y)**2;if(!l2)return distance(p,a);let t=((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/l2;t=Math.max(0,Math.min(1,t));return distance(p,{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y)});}

  canvas.addEventListener('pointerdown',e=>{
    canvas.setPointerCapture(e.pointerId);const sp=pointer(e),p=screenToWorld(sp);if(tool==='pan'||spaceDown||e.button===1){dragging={type:'pan',start:sp,panX:view.panX,panY:view.panY};return;}
    if(tool==='measure'){if(measurePoints.length===2)measurePoints=[];measurePoints.push({x:snap(p.x),y:snap(p.y)});render();return;}
    const handle=selectedHandle(p);if(handle){const o=getObject();if(o&&!o.locked){snapshot();dragging={type:handle,start:p,orig:clone(o),startAngle:Math.atan2(p.y-o.y,p.x-o.x)};return;}}
    const hit=findAt(p);
    if(hit?.kind==='furniture'&&e.shiftKey){const ids=selected?.kind==='multi'?[...selected.ids]:selected?.kind==='furniture'?[selected.id]:[],i=ids.indexOf(hit.id);i>=0?ids.splice(i,1):ids.push(hit.id);selected=ids.length>1?{kind:'multi',ids}:ids.length?{kind:'furniture',id:ids[0]}:null;updateProperties();render();return;}
    if(hit?.kind==='furniture'&&selected?.kind==='multi'&&selected.ids.includes(hit.id)){snapshot();dragging={type:'multi',start:p,origins:selected.ids.map(id=>{const o=state.furniture.find(x=>x.id===id);return{id,x:o.x,y:o.y}})};render();return;}
    if((!hit||hit.kind==='space')&&tool==='select'){if(!e.shiftKey)selected=null;selectionRect={start:p,end:p,additive:e.shiftKey};dragging={type:'selection'};updateProperties();render();return;}
    selected=hit;updateProperties();if(hit&&hit.kind!=='space'){const o=getObject(hit);if(o?.locked&&!['vertices','walls'].includes(tool))return render();snapshot();if(hit.kind==='vertex')dragging={type:'vertex',start:p,orig:{x:o.x,y:o.y}};else if(hit.kind==='wall')dragging={type:'wall',start:p,origStart:clone(o.start),origEnd:clone(o.end)};else if(hit.kind==='glass')dragging={type:hit.endpoint?'glass-end':'glass',endpoint:hit.endpoint,start:p,origStart:clone(o.start),origEnd:clone(o.end)};else dragging={type:'object',start:p,orig:{x:o.x,y:o.y}};}render();
  });
  function objectSnapPosition(o,x,y){snapGuides=[];if(!state.settings.objectSnap||selected?.kind!=='furniture')return{x,y};for(const peer of state.furniture){if(peer.id===o.id)continue;if(Math.abs(peer.x-x)<=10){x=peer.x;snapGuides.push({x1:x,y1:Math.min(y,peer.y)-100,x2:x,y2:Math.max(y,peer.y)+100});}if(Math.abs(peer.y-y)<=10){y=peer.y;snapGuides.push({x1:Math.min(x,peer.x)-100,y1:y,x2:Math.max(x,peer.x)+100,y2:y});}const gap=Math.abs(peer.y-y)-(peer.h+o.h)/2;if(Math.abs(gap-80)<=10)snapGuides.push({x1:x,y1:Math.min(y,peer.y),x2:x,y2:Math.max(y,peer.y),label:'80 cm'});}const box={l:x-o.w/2,r:x+o.w/2,t:y-o.h/2,b:y+o.h/2};for(const [a,b] of boundarySegments()){if(a.x===b.x){if(Math.abs(box.l-a.x)<12)x+=a.x-box.l;if(Math.abs(box.r-a.x)<12)x+=a.x-box.r;}if(a.y===b.y){if(Math.abs(box.t-a.y)<12)y+=a.y-box.t;if(Math.abs(box.b-a.y)<12)y+=a.y-box.b;}}return{x,y};}
  function boundarySegments(){const vs=state.roomBoundary.vertices;return vs.map((v,i)=>[v,vs[(i+1)%vs.length]]);}
  canvas.addEventListener('pointermove',e=>{if(!dragging)return;const sp=pointer(e);if(dragging.type==='pan'){view.panX=dragging.panX+sp.x-dragging.start.x;view.panY=dragging.panY+sp.y-dragging.start.y;render();return;}const p=screenToWorld(sp);if(dragging.type==='selection'){selectionRect.end=p;render();return;}if(dragging.type==='multi'){const dx=snap(p.x-dragging.start.x),dy=snap(p.y-dragging.start.y);dragging.origins.forEach(orig=>{const o=state.furniture.find(x=>x.id===orig.id);o.x=orig.x+dx;o.y=orig.y+dy;});render();return;}const dx=p.x-dragging.start.x,dy=p.y-dragging.start.y,o=getObject();if(!o)return;if(dragging.type==='rotate'){o.rotation=(dragging.orig.rotation+(Math.atan2(p.y-o.y,p.x-o.x)-dragging.startAngle)*180/Math.PI+360)%360;}else if(dragging.type==='resize'){const q=localPoint(p,o);o.w=Math.max(20,Math.abs(q.x)*2);o.h=Math.max(20,Math.abs(q.y)*2);}else if(dragging.type==='vertex'){let nx=dragging.orig.x+dx,ny=dragging.orig.y+dy;if(e.shiftKey){Math.abs(dx)>Math.abs(dy)?ny=dragging.orig.y:nx=dragging.orig.x;}o.x=e.ctrlKey||e.metaKey?nx:snap(nx);o.y=e.ctrlKey||e.metaKey?ny:snap(ny);}else if(dragging.type==='wall'||dragging.type==='glass'){o.start.x=snap(dragging.origStart.x+dx);o.start.y=snap(dragging.origStart.y+dy);o.end.x=snap(dragging.origEnd.x+dx);o.end.y=snap(dragging.origEnd.y+dy);}else if(dragging.type==='glass-end'){const target=dragging.endpoint==='start'?o.start:o.end;target.x=snap(p.x);target.y=snap(p.y);}else{const pos=objectSnapPosition(o,snap(dragging.orig.x+dx),snap(dragging.orig.y+dy));o.x=pos.x;o.y=pos.y;}updateProperties();render();});
  canvas.addEventListener('pointerup',()=>{if(dragging?.type==='selection'&&selectionRect){const l=Math.min(selectionRect.start.x,selectionRect.end.x),r=Math.max(selectionRect.start.x,selectionRect.end.x),t=Math.min(selectionRect.start.y,selectionRect.end.y),b=Math.max(selectionRect.start.y,selectionRect.end.y),hits=state.furniture.filter(o=>{if(o.locked)return false;const q=aabb(o);return q.r>=l&&q.l<=r&&q.b>=t&&q.t<=b;}).map(o=>o.id),old=selectionRect.additive?(selected?.kind==='multi'?selected.ids:selected?.kind==='furniture'?[selected.id]:[]):[],ids=[...new Set([...old,...hits])];selected=ids.length>1?{kind:'multi',ids}:ids.length?{kind:'furniture',id:ids[0]}:null;selectionRect=null;updateProperties();render();}else if(dragging&&dragging.type!=='pan')commit();snapGuides=[];dragging=null;});
  canvas.addEventListener('dblclick',e=>{if(tool!=='vertices')return;const p=screenToWorld(pointer(e)),vs=state.roomBoundary.vertices;let best={i:-1,d:Infinity};for(let i=0;i<vs.length;i++){const d=pointSegmentDistance(p,vs[i],vs[(i+1)%vs.length]);if(d<best.d)best={i,d};}if(best.d<18/view.zoom){snapshot();vs.splice(best.i+1,0,{id:uid('v'),x:snap(p.x),y:snap(p.y)});selected={kind:'vertex',index:best.i+1};commit('새 꼭짓점을 추가했습니다.');}});
  canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(view.zoom*(e.deltaY>0?.9:1.1),pointer(e));},{passive:false});

  function setTool(next){tool=next;measurePoints=[];$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#mode-label').textContent={select:'가구 배치 · 객체 선택',vertices:'도면 편집 · 꼭짓점',walls:'도면 편집 · 벽선',measure:'거리 측정',pan:'화면 이동'}[tool];canvas.style.cursor=tool==='pan'?'grab':['vertices','walls'].includes(tool)?'crosshair':'default';render();}
  $('#tools').addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool);});
  let libraryDrag=null,libraryDragWasDrop=false;
  $('#furniture-list').addEventListener('click',e=>{const b=e.target.closest('[data-furniture]');if(!b)return;if(libraryDragWasDrop){libraryDragWasDrop=false;return;}addFurniture(b.dataset.furniture);});
  function addFurniture(type,position){const t=furnitureTypes[type],center=position||screenToWorld({x:wrap.clientWidth/2,y:wrap.clientHeight/2});snapshot();const count=state.furniture.filter(o=>o.type===type).length+1,o={id:uid(type),type,name:t.numbered===false?t.name:`${t.name} ${count}`,x:snap(center.x),y:snap(center.y),w:t.w,h:t.h,rotation:0,color:t.color,seats:t.seats,space:t.space,opacity:1,locked:false,groupId:null};state.furniture.push(o);selected={kind:'furniture',id:o.id};setTool('select');commit(`${t.name}을(를) 추가했습니다.`);$('#onboarding').hidden=true;}
  $$('#furniture-list [draggable="true"]').forEach(b=>b.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/aiad-furniture',b.dataset.furniture);e.dataTransfer.effectAllowed='copy';}));
  wrap.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('text/aiad-furniture')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
  wrap.addEventListener('drop',e=>{const type=e.dataTransfer.getData('text/aiad-furniture');if(!type)return;e.preventDefault();addFurniture(type,screenToWorld(pointer(e)));});
  $$('#furniture-list [data-furniture]').forEach(b=>{b.draggable=false;b.addEventListener('pointerdown',e=>{libraryDrag={type:b.dataset.furniture,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,active:false};});});
  window.addEventListener('pointermove',e=>{if(!libraryDrag)return;libraryDrag.x=e.clientX;libraryDrag.y=e.clientY;if(!libraryDrag.active&&Math.hypot(e.clientX-libraryDrag.startX,e.clientY-libraryDrag.startY)>7){libraryDrag.active=true;document.body.classList.add('library-dragging');}});
  window.addEventListener('pointerup',e=>{if(!libraryDrag)return;const r=wrap.getBoundingClientRect();if(libraryDrag.active&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){libraryDragWasDrop=true;setTimeout(()=>{libraryDragWasDrop=false;},0);addFurniture(libraryDrag.type,screenToWorld({x:e.clientX-r.left,y:e.clientY-r.top}));}document.body.classList.remove('library-dragging');libraryDrag=null;});
  $('.category-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;$$('.category-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('#furniture-list>button').forEach(x=>x.hidden=b.dataset.category!=='all'&&x.dataset.category!==b.dataset.category);});
  function makeFurniture(type,x,y,rotation=0){const t=furnitureTypes[type],count=(state.furniture||[]).filter(o=>o.type===type).length+1;return{id:uid(type),type,name:t.numbered===false?t.name:`${t.name} ${count}`,x,y,w:t.w,h:t.h,rotation,color:t.color,seats:t.seats,space:t.space,opacity:1,locked:false,groupId:null};}
  $$('[data-add]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.add;if(!['vertices','walls'].includes(tool))return showToast('도면 편집 또는 벽 편집 모드에서 추가할 수 있습니다.');const center=screenToWorld({x:wrap.clientWidth/2,y:wrap.clientHeight/2});snapshot();if(['wall','glass','window'].includes(type)){const obj={id:uid(type),type:type==='glass'?'glass-wall':type,name:type==='glass'?'유리 파티션':type==='window'?'창문':'내부 벽',label:type==='glass'?'유리 파티션':type==='window'?'창문':'내부 벽',start:{x:snap(center.x-60),y:snap(center.y)},end:{x:snap(center.x+60),y:snap(center.y)},startPoint:{x:snap(center.x-60),y:snap(center.y)},endPoint:{x:snap(center.x+60),y:snap(center.y)},thickness:type==='wall'?12:8,locked:false};(type==='wall'?state.walls:type==='glass'?state.glassWalls:state.windows).push(obj);selected=type==='glass'?{kind:'glass',id:obj.id}:null;commit(`${obj.name}을(를) 추가했습니다.`);return;}if(type==='door'){const d={id:uid('door'),type:'door',name:'출입문',x:snap(center.x),y:snap(center.y),width:90,rotation:0,openingDirection:'inward-up-left',openingAngle:90,locked:false};state.doors.push(d);selected={kind:'door',id:d.id};commit('문을 추가했습니다.');return;}const sizes={column:[50,50],ac:[110,35],distribution:[24,62],outlet:[12,12],lan:[12,12]},labels={column:'기둥',ac:'에어컨',distribution:'배전함',outlet:'콘센트',lan:'LAN'},[w,h]=sizes[type]||[50,50],o={id:uid(type),type,name:labels[type],label:labels[type],x:snap(center.x),y:snap(center.y),w,h,width:w,height:h,rotation:0,space:'common',color:type==='column'?'#526077':'#cad3de',locked:false};state.structures.push(o);selected={kind:'structure',id:o.id};commit(`${o.name}을(를) 추가했습니다.`);}));

  function updateProperties(){
    const multi=selected?.kind==='multi',count=multi?selected.ids.length:0;$('#multi-toolbar').hidden=!multi;$('#multi-count').textContent=`${count}개 선택`;const o=getObject(),form=$('#property-form'),empty=$('#empty-properties');if(!o){form.hidden=true;empty.hidden=false;$('#selection-badge').textContent=multi?`${count}개`:'없음';return;}form.hidden=false;empty.hidden=true;
    const linear=['glass','wall'].includes(selected.kind),isSpace=selected.kind==='space';$('#selection-badge').textContent={vertex:'꼭짓점',glass:'유리벽',wall:'일반 벽',door:'문',space:'공간'}[selected.kind]||o.name||o.type;$('#prop-name').value=o.name||o.id;
    $('#prop-x').value=Math.round(linear?o.start.x:isSpace?o.bounds.x:o.x);$('#prop-y').value=Math.round(linear?o.start.y:isSpace?o.bounds.y:o.y);$('#prop-w').value=Math.round(linear?distance(o.start,o.end):selected.kind==='door'?o.width:isSpace?o.bounds.w:o.w||1);$('#prop-h').value=Math.round(linear?o.thickness:selected.kind==='door'?o.openingAngle:isSpace?o.bounds.h:o.h||1);
    $('#prop-rotation').value=o.rotation||0;$('#rotation-value').textContent=`${o.rotation||0}°`;$('#prop-space').value=isSpace?o.type:(o.space||'common');$('#prop-color').value=/^#[0-9a-f]{6}$/i.test(o.color||'')?o.color:'#8793a7';$('#prop-locked').checked=!!o.locked;
    $('#prop-name').disabled=['vertex','wall'].includes(selected.kind);$('#prop-space').disabled=!['furniture','structure','space'].includes(selected.kind);$('#prop-color').disabled=!['furniture','structure'].includes(selected.kind);$('#prop-locked').disabled=['vertex','wall','space'].includes(selected.kind);$('#prop-h').disabled=selected.kind==='vertex';$('#prop-rotation').disabled=['vertex','glass','wall','space'].includes(selected.kind);$('#wall-controls').hidden=!linear;$('#door-direction-field').hidden=selected.kind!=='door';if(selected.kind==='door')$('#prop-door-direction').value=o.openingDirection;
  }
  function setLineLength(o,length,anchor){length=Math.max(1,length);const old=distance(o.start,o.end)||1,ux=(o.end.x-o.start.x)/old,uy=(o.end.y-o.start.y)/old;if(anchor==='end'){o.start.x=o.end.x-ux*length;o.start.y=o.end.y-uy*length;}else if(anchor==='center'){const cx=(o.start.x+o.end.x)/2,cy=(o.start.y+o.end.y)/2;o.start.x=cx-ux*length/2;o.start.y=cy-uy*length/2;o.end.x=cx+ux*length/2;o.end.y=cy+uy*length/2;}else{o.end.x=o.start.x+ux*length;o.end.y=o.start.y+uy*length;}}
  $('#property-form').addEventListener('change',e=>{const o=getObject();if(!o)return;snapshot();const id=e.target.id,val=['number','range'].includes(e.target.type)?Number(e.target.value):e.target.value,linear=['glass','wall'].includes(selected.kind),isSpace=selected.kind==='space';
    if(id==='prop-name'&&o.name!=null)o.name=val;if(id==='prop-space'){if(isSpace)o.type=val;else o.space=val;}if(id==='prop-color')o.color=val;if(id==='prop-locked')o.locked=e.target.checked;if(id==='prop-door-direction')o.openingDirection=val;
    if(linear){if(id==='prop-x'){const dx=val-o.start.x;o.start.x+=dx;o.end.x+=dx}if(id==='prop-y'){const dy=val-o.start.y;o.start.y+=dy;o.end.y+=dy}if(id==='prop-w')setLineLength(o,val,$('#wall-anchor').value);if(id==='prop-h'&&selected.kind==='glass')o.thickness=Math.max(1,val);}
    else if(isSpace){if(id==='prop-x')o.bounds.x=val;if(id==='prop-y')o.bounds.y=val;if(id==='prop-w')o.bounds.w=Math.max(1,val);if(id==='prop-h')o.bounds.h=Math.max(1,val);}
    else if(selected.kind==='door'){if(id==='prop-x')o.x=val;if(id==='prop-y')o.y=val;if(id==='prop-w')o.width=Math.max(1,val);if(id==='prop-h')o.openingAngle=Math.max(10,Math.min(180,val));if(id==='prop-rotation')o.rotation=val;}
    else{if(id==='prop-x')o.x=val;if(id==='prop-y')o.y=val;if(id==='prop-w'&&o.w!=null)o.w=Math.max(1,val);if(id==='prop-h'&&o.h!=null)o.h=Math.max(1,val);if(id==='prop-rotation')o.rotation=val;}commit();});
  $('#prop-rotation').addEventListener('input',e=>{$('#rotation-value').textContent=`${e.target.value}°`;});
  $('#properties').addEventListener('click',e=>{const b=e.target.closest('[data-prop]');if(!b)return;const action=b.dataset.prop,o=getObject();if(action==='delete')deleteSelected();if(action==='duplicate')duplicateSelected();if(action==='rotate'&&o?.rotation!=null){snapshot();o.rotation=(o.rotation+90)%360;commit();}if(['horizontal','vertical'].includes(action)&&['wall','glass'].includes(selected?.kind)){snapshot();if(action==='horizontal')o.end.y=o.start.y;else o.end.x=o.start.x;commit(`${action==='horizontal'?'수평':'수직'}으로 정렬했습니다.`);}if(action==='split'&&['wall','glass'].includes(selected?.kind))splitSelectedLine();if(action==='merge')mergeSelectedWall();});
  function splitSelectedLine(){const o=getObject();if(!o)return;snapshot();if(selected.kind==='wall'){const m={id:uid('v'),x:(o.start.x+o.end.x)/2,y:(o.start.y+o.end.y)/2};state.roomBoundary.vertices.splice(selected.index+1,0,m);selected={kind:'wall',index:selected.index,id:`wall-${selected.index}`};}else{const m={x:(o.start.x+o.end.x)/2,y:(o.start.y+o.end.y)/2},copy={...clone(o),id:uid('glass'),start:clone(m)};o.end=clone(m);state.glassWalls.push(copy);selected={kind:'glass',id:copy.id};}commit('선분을 두 구간으로 나눴습니다.');}
  function mergeSelectedWall(){if(selected?.kind!=='wall')return showToast('일반 벽에서만 인접 벽을 병합할 수 있습니다.');if(state.roomBoundary.vertices.length<=3)return; snapshot();state.roomBoundary.vertices.splice((selected.index+1)%state.roomBoundary.vertices.length,1);selected=null;commit('인접 벽을 병합했습니다.');}
  function deleteSelected(){if(!selected)return;if(selected.kind==='multi'){snapshot();state.furniture=state.furniture.filter(x=>!selected.ids.includes(x.id));}else if(selected.kind==='vertex'||selected.kind==='wall'){if(state.roomBoundary.vertices.length<=3)return showToast('꼭짓점은 최소 3개가 필요합니다.');snapshot();state.roomBoundary.vertices.splice(selected.kind==='vertex'?selected.index:(selected.index+1)%state.roomBoundary.vertices.length,1);}else if(selected.kind==='furniture'){snapshot();state.furniture=state.furniture.filter(x=>x.id!==selected.id);}else if(selected.kind==='structure'){snapshot();state.structures=state.structures.filter(x=>x.id!==selected.id);}else if(selected.kind==='door'){snapshot();state.doors=state.doors.filter(x=>x.id!==selected.id);}else if(selected.kind==='glass'){if(state.glassWalls.length<=1)return showToast('기본 유리 파티션은 최소 한 구간을 유지합니다.');snapshot();state.glassWalls=state.glassWalls.filter(x=>x.id!==selected.id);}else return showToast('이 객체는 삭제할 수 없습니다.');selected=null;commit('선택한 객체를 삭제했습니다.');}
  function duplicateSelected(){if(selected?.kind==='multi'){snapshot();const copies=selected.ids.map(id=>{const o=state.furniture.find(x=>x.id===id),c={...clone(o),id:uid(o.type),name:`${o.name} 복사본`,x:o.x+state.gridSize,y:o.y+state.gridSize};state.furniture.push(c);return c.id;});selected={kind:'multi',ids:copies};return commit(`${copies.length}개 객체를 복제했습니다.`);}const o=getObject();if(!o||!['furniture','structure','door'].includes(selected.kind))return showToast('이 객체는 복제할 수 없습니다.');snapshot();const copy={...clone(o),id:uid(o.type),name:`${o.name} 복사본`,x:o.x+state.gridSize,y:o.y+state.gridSize};const list=selected.kind==='furniture'?state.furniture:selected.kind==='structure'?state.structures:state.doors;list.push(copy);selected={kind:selected.kind,id:copy.id};commit('객체를 복제했습니다.');}

  function polygonArea(vs){let sum=0;for(let i=0;i<vs.length;i++){const a=vs[i],b=vs[(i+1)%vs.length];sum+=a.x*b.y-b.x*a.y;}return Math.abs(sum)/2;}
  function pointInPolygon(p,vs){let inside=false;for(let i=0,j=vs.length-1;i<vs.length;j=i++){const a=vs[i],b=vs[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x))inside=!inside;}return inside;}
  function rectCorners(o){const a=(o.rotation||0)*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return[[-o.w/2,-o.h/2],[o.w/2,-o.h/2],[o.w/2,o.h/2],[-o.w/2,o.h/2]].map(([x,y])=>({x:o.x+x*c-y*s,y:o.y+x*s+y*c}));}
  function aabb(o){const c=rectCorners(o);return{l:Math.min(...c.map(p=>p.x)),r:Math.max(...c.map(p=>p.x)),t:Math.min(...c.map(p=>p.y)),b:Math.max(...c.map(p=>p.y))};}
  function overlap(a,b){const A=aabb(a),B=aabb(b);return A.l<B.r&&A.r>B.l&&A.t<B.b&&A.b>B.t;}
  function getWarnings(){const out=[],fs=state.furniture,vs=state.roomBoundary.vertices,minGlass=30;fs.forEach(o=>{if(rectCorners(o).some(p=>!pointInPolygon(p,vs)))out.push({text:`${o.name}이(가) 연구실 외곽선 밖으로 벗어났습니다.`,ids:[o.id]});state.doors.forEach(d=>{const zone={x:d.x+d.width/2,y:d.y-d.width/2,w:d.width,h:d.width,rotation:d.rotation||0};if(overlap(o,zone))out.push({text:`${o.name}이(가) ${d.name} 열림 영역을 침범하고 있습니다.`,ids:[o.id,d.id]});});state.glassWalls.forEach(g=>{const box=aabb(o),vertical=Math.abs(g.end.y-g.start.y)>Math.abs(g.end.x-g.start.x),radius=vertical?(box.r-box.l)/2:(box.b-box.t)/2,gap=pointSegmentDistance({x:o.x,y:o.y},g.start,g.end)-radius;if(gap<minGlass&&o.type!=='monitor')out.push({text:`${o.name}의 유리벽 안전거리가 ${Math.max(0,Math.round(gap))}cm로 기준 ${minGlass}cm보다 좁습니다.`,ids:[o.id,g.id]});});});for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++)if(overlap(fs[i],fs[j]))out.push({text:`${fs[i].name}과(와) ${fs[j].name}이(가) 서로 겹칩니다.`,ids:[fs[i].id,fs[j].id]});const fridge=fs.find(o=>o.type==='fridge');if(fridge){const access={x:fridge.x-100*Math.cos((fridge.rotation||0)*Math.PI/180),y:fridge.y-100*Math.sin((fridge.rotation||0)*Math.PI/180),w:120,h:100,rotation:fridge.rotation||0};const blocker=fs.find(o=>o.id!==fridge.id&&overlap(o,access));if(blocker)out.push({text:`${blocker.name}이(가) 냉장고 전면 접근 공간을 막고 있습니다.`,ids:[fridge.id,blocker.id]});}const monitor=fs.find(o=>o.type==='monitor');if(monitor){const front={x:monitor.x-100*Math.sin((monitor.rotation||0)*Math.PI/180),y:monitor.y+100*Math.cos((monitor.rotation||0)*Math.PI/180),w:monitor.w,h:180,rotation:monitor.rotation||0};const blocker=fs.find(o=>!['monitor','meetingTable','meetingChair'].includes(o.type)&&overlap(o,front));if(blocker)out.push({text:`${blocker.name}이(가) 대형 모니터 전면 시야를 가리고 있습니다.`,ids:[monitor.id,blocker.id]});}if(selfIntersects(vs))out.push({text:'연구실 외곽선이 자기 교차하여 저장할 수 없습니다.',ids:[]});return out;}
  function orient(a,b,c){return Math.sign((b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x));}
  function segmentsCross(a,b,c,d){return orient(a,b,c)!==orient(a,b,d)&&orient(c,d,a)!==orient(c,d,b);}
  function selfIntersects(vs){for(let i=0;i<vs.length;i++)for(let j=i+1;j<vs.length;j++){if(Math.abs(i-j)<=1||(i===0&&j===vs.length-1))continue;if(segmentsCross(vs[i],vs[(i+1)%vs.length],vs[j],vs[(j+1)%vs.length]))return true;}return false;}
  function meetingMetrics(){const fs=state.furniture,m=fs.find(o=>o.type==='monitor'),t=fs.find(o=>o.type==='meetingTable'),chairs=fs.filter(o=>o.type==='meetingChair'),fridge=fs.find(o=>o.type==='fridge'),doorBlocked=getWarnings().some(w=>w.ids.some(id=>state.doors.some(d=>d.id===id)));return{distance:m&&t?Math.max(0,Math.round(distance(m,t)-Math.max(m.w,t.w)/2)):null,chairs:chairs.length,access:!doorBlocked,fridge:!!fridge};}
  function minimumAisle(){if(!state.furniture.length)return null;let min=Infinity;state.furniture.forEach(o=>{const radius=Math.max(o.w,o.h)/2;boundarySegments().forEach(([a,b])=>{const gap=pointSegmentDistance(o,a,b)-radius;if(gap>=0)min=Math.min(min,gap);});});for(let i=0;i<state.furniture.length;i++)for(let j=i+1;j<state.furniture.length;j++){const a=state.furniture[i],b=state.furniture[j],gap=distance(a,b)-(Math.max(a.w,a.h)+Math.max(b.w,b.h))/2;if(gap>=0)min=Math.min(min,gap);}return Number.isFinite(min)?Math.round(min):null;}
  function updateAnalysis(){const area=polygonArea(state.roomBoundary.vertices)/10000,occupied=state.furniture.reduce((s,o)=>s+o.w*o.h,0)/10000,seats=state.furniture.reduce((s,o)=>s+(o.seats||0),0),deskCount=state.furniture.filter(o=>['desk','existingDesk'].includes(o.type)).length,chairCount=state.furniture.filter(o=>['chair','meetingChair'].includes(o.type)).length,warnings=getWarnings(),aisle=minimumAisle(),mm=meetingMetrics();$('#stat-area').textContent=`${area.toFixed(1)} m²`;$('#stat-occupied').textContent=`${occupied.toFixed(1)} m²`;$('#stat-occupancy').textContent=`${area?Math.round(occupied/area*100):0}%`;$('#stat-remaining').textContent=`${Math.max(0,area-occupied).toFixed(1)} m²`;$('#stat-desks').textContent=deskCount;$('#stat-chairs').textContent=chairCount;$('#stat-seats').textContent=seats;$('#stat-meeting-seats').textContent=mm.chairs;$('#stat-aisle').textContent=aisle==null?'—':`${aisle} cm`;$('#stat-warnings').textContent=warnings.length;$('#warning-count').textContent=warnings.length;$('#warning-list').innerHTML=warnings.length?warnings.map(w=>`<li class="warning-item">${escapeHtml(w.text)}</li>`).join(''):'<li class="all-clear"><span>✓</span>현재 배치에 문제가 없습니다.</li>';$('#meeting-analysis').innerHTML=`<div class="meeting-metric"><span>모니터–테이블 거리</span><b>${mm.distance==null?'미배치':`${mm.distance} cm`}</b></div><div class="meeting-metric"><span>회의용 좌석</span><b>${mm.chairs}석</b></div><div class="meeting-metric"><span>출입구 접근</span><b>${mm.access?'확보':'차단'}</b></div><div class="meeting-metric"><span>냉장고</span><b>${mm.fridge?'배치됨':'미배치'}</b></div>`;updatePrintReport({area,occupied,seats,deskCount,chairCount,warnings,aisle,mm});}
  function updatePrintReport(a){$('#print-meta').textContent=`${state.projectName} · ${new Date().toLocaleDateString('ko-KR')} · ${state.orientation.label} · 축척 ${$('#scale-label').textContent}`;$('#print-analysis').textContent=`전체 면적: ${a.area.toFixed(1)} m²\n가구 점유 면적: ${a.occupied.toFixed(1)} m²\n잔여 면적: ${(a.area-a.occupied).toFixed(1)} m²\n책상: ${a.deskCount}개\n의자: ${a.chairCount}개\n전체 좌석: ${a.seats}석\n회의 좌석: ${a.mm.chairs}석\n최소 통로 폭: ${a.aisle==null?'—':`${a.aisle} cm`}\n경고: ${a.warnings.length}건`;$('#print-targets').textContent='사용자 구분 없는 공통 가구 유형을 사용합니다.';$('#print-furniture').textContent=state.furniture.map(o=>`${o.name} · ${o.w}×${o.h}cm · (${Math.round(o.x)}, ${Math.round(o.y)})`).join('\n')||'가구 없음';$('#print-warnings').textContent=a.warnings.length?a.warnings.map((w,i)=>`${i+1}. ${w.text}`).join('\n'):'경고 없음';}
  function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

  $('[data-action="undo"]').addEventListener('click',undo);$('[data-action="redo"]').addEventListener('click',redo);
  $('[data-action="save"]').addEventListener('click',saveNow);
  function saveNow(){if(selfIntersects(state.roomBoundary.vertices))return showToast('자기 교차 외곽선은 저장할 수 없습니다.');backupDraft();if(window.AIADProjectManager)return window.AIADProjectManager.saveCurrent(true);showToast('공용 저장소를 준비하는 중입니다. 임시 백업은 완료되었습니다.');}
  function rotateProject(degrees){snapshot();rotateData(state,degrees,true);state.orientation.rotationDegrees=((state.orientation.rotationDegrees+degrees+540)%360)-180;state.orientation.label=state.orientation.rotationDegrees===-90?'왼쪽으로 90도 회전':`${state.orientation.rotationDegrees}도 회전`;selected=null;commit(`${degrees<0?'왼쪽':'오른쪽'}으로 90도 회전했습니다.`);fitView();}
  $('[data-action="export-json"]').addEventListener('click',()=>{if(selfIntersects(state.roomBoundary.vertices))return showToast('자기 교차 외곽선은 내보낼 수 없습니다.');download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'aiad-layout-v2.json');});
  $('[data-action="import-json"]').addEventListener('click',()=>$('#json-file').click());
  $('#json-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{let data=JSON.parse(await f.text());if(!data.roomBoundary?.vertices?.length)throw new Error();snapshot();if(!data.orientation){localStorage.setItem(`aiad-import-backup-${Date.now()}`,JSON.stringify(data));const rotate=confirm('구버전 JSON입니다. 세로형 도면을 왼쪽으로 90도 회전하여 가져올까요?');data=migrateLegacy(data,rotate);}else data=normalizeV2(data);window.AIADProjectManager?.detachCurrent();state=data;selected=null;commit('배치안을 불러왔습니다. 새 공용 배치안으로 저장해 주세요.');fitView();}catch(err){showToast('지원하지 않거나 손상된 JSON 파일입니다.');}e.target.value='';});
  $('[data-action="png"]').addEventListener('click',()=>{const scale=Number(prompt('PNG 해상도 배율을 입력하세요 (1, 2, 4)','2'));if(![1,2,4].includes(scale))return showToast('해상도는 1, 2, 4 중에서 선택하세요.');const includeGrid=confirm('PNG에 배경 격자를 포함할까요?'),oldSel=selected,oldGrid=state.settings.showGrid;selected=null;state.settings.showGrid=includeGrid;render();const out=document.createElement('canvas');out.width=canvas.width*scale;out.height=canvas.height*scale;out.getContext('2d').drawImage(canvas,0,0,out.width,out.height);out.toBlob(b=>download(b,`aiad-layout-${scale}x.png`));selected=oldSel;state.settings.showGrid=oldGrid;render();});
  $('[data-action="print"]').addEventListener('click',()=>window.print());
  const dialog=$('#help-dialog');$('[data-action="help"]').addEventListener('click',()=>dialog.showModal());$('#help-dialog .dialog-close').addEventListener('click',()=>dialog.close());$('.compare-close').addEventListener('click',()=>$('#compare-dialog').close());
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  $('#grid-size').value=String(state.gridSize||50);$('#grid-size').addEventListener('change',e=>{snapshot();state.gridSize=Number(e.target.value);$('#grid-label').textContent=`${state.gridSize} cm`;commit();});
  $('#unit').value=state.unit||'cm';$('#unit').addEventListener('change',e=>{state.unit=e.target.value;showToast(`표시 단위를 ${state.unit}(으)로 변경했습니다.`);});
  $('#snap').checked=state.settings.snap!==false;$('#snap').addEventListener('change',e=>{state.settings.snap=e.target.checked;commit();});
  $('#object-snap').checked=state.settings.objectSnap!==false;$('#object-snap').addEventListener('change',e=>{state.settings.objectSnap=e.target.checked;commit();});
  $('#grid-toggle').classList.toggle('active',state.settings.showGrid!==false);$('#grid-toggle').addEventListener('click',e=>{state.settings.showGrid=!state.settings.showGrid;e.currentTarget.classList.toggle('active',state.settings.showGrid);render();});
  $('#dimension-toggle').classList.toggle('active',state.settings.showDimensions!==false);$('#dimension-toggle').addEventListener('click',e=>{state.settings.showDimensions=!state.settings.showDimensions;e.currentTarget.classList.toggle('active',state.settings.showDimensions);render();});
  $('#header-dimensions').classList.toggle('active',state.settings.showDimensions!==false);$('#header-dimensions').addEventListener('click',e=>{state.settings.showDimensions=!state.settings.showDimensions;e.currentTarget.classList.toggle('active',state.settings.showDimensions);$('#dimension-toggle').classList.toggle('active',state.settings.showDimensions);commit();});
  $('#fit').addEventListener('click',fitView);$('#focus-selected').addEventListener('click',()=>{const o=getObject();if(!o||o.x==null)return showToast('중심에 맞출 객체를 선택하세요.');view.panX=wrap.clientWidth/2-o.x*view.zoom;view.panY=wrap.clientHeight/2-o.y*view.zoom;render();});$('#zoom-in').addEventListener('click',()=>setZoom(view.zoom*1.2));$('#zoom-out').addEventListener('click',()=>setZoom(view.zoom/1.2));
  window.addEventListener('keydown',e=>{const tag=document.activeElement.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(e.code==='Space'){spaceDown=true;e.preventDefault();}if(e.key==='Alt'){altDown=true;render();}if(e.key==='Delete')deleteSelected();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveNow();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selected={kind:'multi',ids:state.furniture.filter(o=>!o.locked).map(o=>o.id)};showToast(`가구 ${selected.ids.length}개를 선택했습니다.`);updateProperties();render();}const map={v:'select',n:'vertices',w:'walls',m:'measure',h:'pan'};if(map[e.key.toLowerCase()])setTool(map[e.key.toLowerCase()]);if(e.key==='Escape'){selected=null;measurePoints=[];updateProperties();render();}});
  window.addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false;if(e.key==='Alt'){altDown=false;render();}});
  $('[data-action="analysis"]').addEventListener('click',()=>{$('#analysis-drawer').hidden=false;});$('[data-action="analysis-close"]').addEventListener('click',()=>{$('#analysis-drawer').hidden=true;});
  $('#onboarding button').addEventListener('click',()=>{$('#onboarding').hidden=true;});
  $$('[data-action="reset-furniture"]').forEach(b=>b.addEventListener('click',()=>{if(!state.furniture.length)return showToast('초기화할 가구가 없습니다.');snapshot();state.furniture=[];selected=null;commit('가구만 초기화했습니다. 공식 도면은 유지됩니다.');}));
  $('[data-action="reset-all"]').addEventListener('click',()=>$('#reset-dialog').showModal());$('#reset-dialog').addEventListener('click',e=>{const a=e.target.dataset.reset;if(a==='cancel')$('#reset-dialog').close();if(a==='confirm'){snapshot();const projectName=state.projectName;state=initial();state.projectName=projectName;selected=null;$('#reset-dialog').close();commit('공식 도면과 가구를 초기화했습니다.');fitView();}});
  function setView(mode){viewMode=mode;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===mode));canvas.hidden=mode==='3d';$('#three-view').hidden=mode!=='3d';$('#three-controls').hidden=mode!=='3d';$('#multi-toolbar').hidden=mode==='3d'||selected?.kind!=='multi';$('.canvas-footer').hidden=mode==='3d';if(mode==='3d'){if(!sceneManager)sceneManager=new window.AIADSceneManager($('#three-view'));if(!sceneManager.ready){showToast('3D 라이브러리를 불러오지 못했습니다. 네트워크를 확인하세요.');setView('2d');return;}sceneManager.build(state);}else{resize();requestAnimationFrame(fitView);}}
  $$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#three-controls').addEventListener('click',e=>{const b=e.target.closest('[data-camera]');if(!b)return;b.dataset.camera==='fit'?sceneManager.fit():sceneManager.setCamera(b.dataset.camera);});$('#wall-visibility').addEventListener('change',e=>sceneManager?.applyWallMode(e.target.value));
  $('#multi-toolbar').addEventListener('click',e=>{const b=e.target.closest('[data-multi]');if(!b||selected?.kind!=='multi')return;const action=b.dataset.multi,items=selected.ids.map(id=>state.furniture.find(x=>x.id===id)).filter(Boolean);if(action==='delete')return deleteSelected();if(action==='duplicate')return duplicateSelected();snapshot();if(action==='group'){const gid=uid('group');items.forEach(o=>o.groupId=gid);}else if(action==='left'){const edge=Math.min(...items.map(o=>aabb(o).l));items.forEach(o=>o.x+=edge-aabb(o).l);}else if(action==='right'){const edge=Math.max(...items.map(o=>aabb(o).r));items.forEach(o=>o.x+=edge-aabb(o).r);}else if(action==='top'){const edge=Math.min(...items.map(o=>aabb(o).t));items.forEach(o=>o.y+=edge-aabb(o).t);}else if(action==='bottom'){const edge=Math.max(...items.map(o=>aabb(o).b));items.forEach(o=>o.y+=edge-aabb(o).b);}else if(action==='hcenter'){const x=items.reduce((s,o)=>s+o.x,0)/items.length;items.forEach(o=>o.x=x);}else if(action==='vcenter'){const y=items.reduce((s,o)=>s+o.y,0)/items.length;items.forEach(o=>o.y=y);}else if(action==='hspace'&&items.length>2){items.sort((a,b)=>a.x-b.x);const step=(items.at(-1).x-items[0].x)/(items.length-1);items.forEach((o,i)=>o.x=items[0].x+step*i);}else if(action==='vspace'&&items.length>2){items.sort((a,b)=>a.y-b.y);const step=(items.at(-1).y-items[0].y)/(items.length-1);items.forEach((o,i)=>o.y=items[0].y+step*i);}commit('다중 객체 작업을 적용했습니다.');});
  new ResizeObserver(()=>{resize();sceneManager?.resize();}).observe(wrap);
  function runSelfTests(){
    const tests=[],check=(name,pass)=>tests.push({name,pass:!!pass});
    const fresh=initial(),g=fresh.glassWalls[0],column=fresh.structures.find(o=>o.id==='column-main');
    const migrated=normalizeV2({...clone(fresh),furniture:[{id:'old-prof',type:'professorLargeDesk',name:'교수님용 큰 책상',x:100,y:100,w:180,h:80,space:'professor'}]});
    const preserved=normalizeV2({...clone(fresh),furniture:[{id:'old-fridge',type:'fridge',name:'냉장고',x:100,y:100,w:80,h:80},{id:'old-sofa',type:'sofa',name:'소파',x:300,y:300,w:180,h:80}]});
    const existingDeskRoundTrip=JSON.parse(JSON.stringify({type:'existingDesk',name:'기존 책상',w:180,h:100}));
    check('v3.1 common model',fresh.version==='3.1.0'&&fresh.room.boundary.length===fresh.roomBoundary.vertices.length);
    check('empty first layout',fresh.activeLayout==='empty'&&fresh.furniture.length===0);
    check('official 800cm west wall',Math.max(...fresh.roomBoundary.vertices.map(v=>v.y))===800);
    check('vertical glass partition',g.start.x===g.end.x&&g.locked);
    check('no upper partition door',!fresh.doors.some(d=>d.id==='door-north'));
    check('no east air conditioner',!fresh.structures.some(o=>o.id==='ac-east'));
    check('corrected column position',column.x===326.5&&column.y===182);
    check('fixed outlets and LAN',fresh.structures.some(o=>o.type==='outlet')&&fresh.structures.some(o=>o.type==='lan'));
    check('single desk and chair types',!!furnitureTypes.desk&&!!furnitureTypes.chair&&!furnitureTypes.profLarge&&!furnitureTypes.gradDesk);
    check('legacy professor migration',migrated.furniture[0].type==='desk'&&migrated.furniture[0].space==='workspace'&&!migrated.targetCounts);
    check('editable polygon',fresh.roomBoundary.vertices.length>=3&&!selfIntersects(fresh.roomBoundary.vertices));
    check('JSON round trip',JSON.parse(JSON.stringify(fresh)).room.fixedFacilities.length===fresh.structures.length);
    check('new furniture defaults',furnitureTypes.existingDesk.w===180&&furnitureTypes.existingDesk.h===100&&furnitureTypes.fridge.w===48&&furnitureTypes.fridge.h===52&&furnitureTypes.sofa.w===240&&furnitureTypes.sofa.h===80);
    check('saved furniture sizes preserved',preserved.furniture[0].w===80&&preserved.furniture[0].h===80&&preserved.furniture[1].w===180&&preserved.furniture[1].h===80);
    check('existing desk JSON round trip',existingDeskRoundTrip.type==='existingDesk'&&existingDeskRoundTrip.w===180&&existingDeskRoundTrip.h===100);
    const result=document.createElement('pre');result.id='self-test-results';result.textContent=JSON.stringify({passed:tests.filter(t=>t.pass).length,total:tests.length,tests},null,2);document.body.appendChild(result);
  }
  function loadProject(data){state=normalizeV2(clone(data));history=[];future=[];selected=null;$('#project-label').textContent=state.projectName;$('#grid-size').value=String(state.gridSize);$('#grid-label').textContent=`${state.gridSize} cm`;$('#snap').checked=state.settings.snap!==false;$('#object-snap').checked=state.settings.objectSnap!==false;updateAnalysis();updateProperties();render();if(viewMode==='3d')sceneManager?.build(state);requestAnimationFrame(fitView);}
  function startBlank(name='빈 연구실'){state=initial();state.projectName=name;history=[];future=[];selected=null;$('#project-label').textContent=name;updateAnalysis();updateProperties();render();requestAnimationFrame(fitView);}
  window.AIAD_APP={getProject:serializeProject,loadProject,startBlank,setProjectName:name=>{state.projectName=name;$('#project-label').textContent=name;},backupDraft,clearDraft:()=>localStorage.removeItem(DRAFT_STORAGE_KEY),hasLegacyProject:()=>Boolean(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_STORAGE_KEY)),getLegacyProject:readLegacyProject,toast:showToast};
  $('#project-label').textContent=state.projectName;$('#grid-label').textContent=`${state.gridSize} cm`;updateAnalysis();updateProperties();resize();requestAnimationFrame(fitView);if(new URLSearchParams(location.search).has('selftest'))runSelfTests();
})();
